AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMessagePeer");
AdfUIComponents.createComponentClass("AdfUIMessages",{componentType:"org.apache.myfaces.trinidad.Messages"});
AdfUIComponents.createComponentClass("AdfRichMessages",{componentType:"oracle.adf.RichMessages",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"message",type:"String"},{name:"text",type:"String"},{name:"globalOnly",type:"Boolean","default":!1},{name:"inline",type:"Boolean","default":!1}],superclass:AdfUIMessages});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMessagesPeer");
AdfDhtmlMessagesPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.SHORT_DESC);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.MESSAGE);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.TEXT);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.GLOBAL_ONLY);AdfDhtmlMessagesPeer._ATTRIBUTE_GLOBAL_ONLY="_afrGlobalOnly";AdfDhtmlMessagesPeer._ATTRIBUTE_MESSAGE="_afrMessage";AdfDhtmlMessagesPeer._ATTRIBUTE_TEXT="_afrText";AdfDhtmlMessagesPeer._HEADER_TEXT_STYLE_CLASS=
"af|messages::header-text";AdfDhtmlMessagesPeer._MESSAGES_INTRO_CLASS="af|messages::intro";AdfDhtmlMessagesPeer._MESSAGES_GROUP_TITLE_CLASS="af|messages::message-group-title";AdfDhtmlMessagesPeer._MESSAGES_TYPE_CLASS="af|messages::type";AdfDhtmlMessagesPeer._MESSAGES_DETAIL_CLASS="af|messages::detail"};
AdfDhtmlMessagesPeer.prototype.componentRemoved=function(a){AdfDhtmlMessagesPeer.superclass.componentRemoved.call(this,a);var b=AdfPage.PAGE,d=b.getDefaultMessageHandlerComponentId(),e=b.getMessageHandlerSlaveComponentId(),f=a.getClientId(),g=!1;if(f==d){for(var g=!0,h;a&&!h;)(a=a.getParent())&&a instanceof AdfRichDocument&&(h=a.getClientId());d=h}f==e&&(AdfMessageUtils.HideMessagesDialog(),g=!0,e=null);g&&b.setDefaultMessageHandlerComponentId(d,e)};
AdfDhtmlMessagesPeer.prototype.isMessagesDialogShowable=function(){return!1};AdfDhtmlMessagesPeer.prototype.setMessagesDialogShown=function(a){};AdfDhtmlMessagesPeer.prototype.GetComponentShortDesc=function(a,b){return AdfAgent.AGENT.getAttribute(b,"title")};AdfDhtmlMessagesPeer.prototype.GetComponentMessage=function(a,b){return AdfAgent.AGENT.getAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_MESSAGE)};
AdfDhtmlMessagesPeer.prototype.GetComponentText=function(a,b){return AdfAgent.AGENT.getAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_TEXT)};AdfDhtmlMessagesPeer.prototype.GetComponentGlobalOnly=function(a,b){return AdfAgent.AGENT.getBooleanAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_GLOBAL_ONLY)};AdfDhtmlMessagesPeer.prototype.MessageShow=function(a,b){this._messageUpdate(a,b,!0)};
AdfDhtmlMessagesPeer.prototype.MessageNotify=function(a,b){AdfDhtmlMessagesPeer.superclass.MessageNotify.call(this,a,b);this._messageUpdate(a,b,!1)};
AdfDhtmlMessagesPeer.prototype._messageUpdate=function(a,b,d){b=AdfPage.PAGE;var e=this.getComponent(),f=e.getClientId(),g=b.getAllMessages(),h=this.getDomElement(),k=this.GetComponentGlobalOnly(e,h),l=g[f],m=0;null!=l&&(m=l.length);if(d&&!AdfMessageUtils.isPageLevelBoxNeeded(b,l,k))for(var n in g)d=g[n],null!=d&&null!=d.compId&&AdfMessageUtils.messageGroupFocus(n);if(AdfMessageUtils.hasMessages(b,m,k)){AdfDomUtils.removeAllNodes(h);n=AdfAgent.AGENT;d=n.getDomDocument().createElement("table");d.summary=
"";d.setAttribute("role","presentation");var p=d.insertRow(-1),m=p.insertCell(-1);null==a&&(a=0);if(k)a=l.maxType;else for(var q in g)l=g[q].maxType,l>a&&(a=l);q=AdfMessageUtils.getIcon(a,!0);m.appendChild(q);m=p.insertCell(-1);q=AdfPage.PAGE.getLookAndFeel();AdfDomUtils.addCSSClassName(m,q.getStyleClass(AdfDhtmlMessagesPeer._HEADER_TEXT_STYLE_CLASS));q=e.getText();null==q?n.setTextContent(m,AdfMessageUtils.getString(a,!0)):n.setTextContent(m,q);h.appendChild(d);a=e.getMessage();a=AdfMessageUtils.getCombinedMessagesDom(f,
a,k);h.appendChild(a);h.style.display=""}else h.style.display="none",AdfDomUtils.removeAllNodes(h),AdfMessageUtils.HideMessagesDialog();b.__queueDescendantResizeNotifySource(e);b.__doDescendantResizeNotify()};