AdfUIComponents.createComponentClass("AdfRichSelectOneListbox",{componentType:"oracle.adf.RichSelectOneListbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"unselectedLabel",type:"String"},{name:"size",type:"Number","default":4}],superclass:AdfUISelectOne});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectOneListbasePeer,"AdfDhtmlSelectOneListboxPeer");
AdfDhtmlSelectOneListboxPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectOne.SELECT_ITEMS,AdfRichSelectOneListbox.LABEL);AdfObject.ensureClassInitialization(AdfRichSelectOneListbox);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectOneListbox.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE);
this._DISABLED_STYLE_CLASS="p_AFDisabled";this._SELECTED_STYLE_CLASS="p_AFSelected";this._SELECTED_ID="_afrSelectedId";this.LIST_HOLDER_ID="listHolder";this._TITLES_POPULATED_EXPANDO="_adfTP"};AdfDhtmlSelectOneListboxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlSelectOneListboxPeer.superclass.InitDomElement.call(this,a,b);this._scrollToSelection(a)};
AdfDhtmlSelectOneListboxPeer.prototype.BindToComponent=function(a,b){AdfDhtmlSelectOneListboxPeer.superclass.BindToComponent.call(this,a,b);var d=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlSelectOneListboxPeer.LIST_HOLDER_ID),e=AdfAgent.AGENT;if((d=e.getElementById(d))&&!d.getAttribute(AdfDhtmlSelectOneListboxPeer._TITLES_POPULATED_EXPANDO)){for(var f=this.GetItemElements(a),g=f.length,h=null,k=e.getPlatform()==AdfAgent.IE_PLATFORM&&7==Math.floor(e.getVersion()),l=0;l<g;l++)h=f[l],(null==h.title||
""==h.title)&&h.setAttribute("title",h.innerHTML),k&&e.disableUserSelect(h);d.setAttribute(AdfDhtmlSelectOneListboxPeer._TITLES_POPULATED_EXPANDO,!0)}};
AdfDhtmlSelectOneListboxPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectOneListboxPeer.superclass.HandleComponentClick.call(this,a);var b=a.getSource(),d=a.getNativeEventTarget();if("LABEL"==AdfAgent.AGENT.getNodeName(d))this.focus(b);else if(this.IsItemEnabled(d)){var e=d.getAttribute(AdfDhtmlSelectOneListbasePeer._ITEM_VALUE_EXPANDO),f=this.getDomElement(),g=this._getSelectedItemElement(b,f);null!=g&&a.getNativeEvent().ctrlKey&&g==d&&(e="");this._validate(b,f,""+e)}};
AdfDhtmlSelectOneListboxPeer.prototype.HandleComponentMouseDown=function(a){a.getNativeEvent().ctrlKey&&a.cancel()};
AdfDhtmlSelectOneListboxPeer.prototype.HandleComponentKeyDown=function(a){var b=a.getNativeEvent(),d=AdfAgent.AGENT.getKeyCode(b),e=a.getSource(),f=this.getDomElement(),g=this._getSelectedItemElement(e,f);a.getNativeEventTarget();switch(d){case AdfKeyStroke.SPACE_KEY:b.ctrlKey&&this._validate(e,f,"");a.cancel();break;case AdfKeyStroke.ENTER_KEY:this.ValidateIfStashedOldValue(e,f);break;case AdfKeyStroke.ARROWUP_KEY:case AdfKeyStroke.ARROWDOWN_KEY:(b=d==AdfKeyStroke.ARROWUP_KEY?this.GetPreviousEnabledItem(g):
this.GetNextEnabledItem(g))||(b=this.GetFirstEnabledItem(e)),b&&(this.StashOldValue(e,f),b=b.getAttribute(AdfDhtmlSelectOneListbasePeer._ITEM_VALUE_EXPANDO),this.SetDisplayValue(e,f,b)),a.cancel()}};AdfDhtmlSelectOneListboxPeer.prototype.HandleComponentBlur=function(a){a=a.getSource();var b=this.getDomElement();this.ValidateIfStashedOldValue(a,b)};
AdfDhtmlSelectOneListboxPeer.prototype.SetDisplayValue=function(a,b,d){var e=AdfDhtmlEditableValuePeer.getContentNode(a,b);AdfAssert.assertString(d);if(!a.getReadOnly()){var f=this.FindItemElementWithValue(a,d);b=this._getSelectedItemElement(a,b);this.SelectItemElement(a,f,b);e.value=d}};AdfDhtmlSelectOneListboxPeer.prototype.GetNoteWindowAlignmentNode=function(a,b){var d=a.getClientId(),d=AdfRichUIPeer.CreateSubId(d,AdfDhtmlSelectOneListboxPeer.LIST_HOLDER_ID);return AdfAgent.AGENT.getElementById(d)};
AdfDhtmlSelectOneListboxPeer.prototype.GetItemElementsParent=function(a){a=a.getClientId();return AdfAgent.AGENT.getElementById(AdfRichUIPeer.CreateSubId(a,AdfDhtmlSelectOneListboxPeer.LIST_HOLDER_ID))};AdfDhtmlSelectOneListboxPeer.prototype._getSelectedItemElement=function(a,b){var d=this.GetSubmittedValue(a,b);return this.FindItemElementWithValue(a,d)};AdfDhtmlSelectOneListboxPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfDhtmlSelectOneListboxPeer.prototype._validate=function(a,b,d){this.SetDisplayValue(a,b,d);this.Validate(a,d)};AdfDhtmlSelectOneListboxPeer.prototype.needsResizeNotify=function(a){return!0};AdfDhtmlSelectOneListboxPeer.prototype.ResizeNotify=function(a,b,d,e){a=this.getComponent();this._scrollToSelection(a)};
AdfDhtmlSelectOneListboxPeer.prototype._scrollToSelection=function(a){var b=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlSelectOneListboxPeer.LIST_HOLDER_ID);if(b=AdfAgent.AGENT.getElementById(b)){var d=this.getDomElement();a=this._getSelectedItemElement(a,d);null!=a&&AdfDomUtils.setScrollTop(b,a.offsetTop)}};