function AdfDashboardDropTarget(a){this.Init(AdfDnDContext.ACTION_MOVE,a)}AdfObject.createSubclass(AdfDashboardDropTarget,AdfStampedDropTarget);AdfDashboardDropTarget.prototype.Init=function(a,b){AdfDashboardDropTarget.superclass.Init.call(this,a);this._allowedFlavors=b};AdfDashboardDropTarget.prototype.GetAllowedFlavors=function(a){return this._allowedFlavors};
AdfDashboardDropTarget.prototype.AcceptDragOverrideIfRejectedByFlavor=function(a,b){var d=a.getDragSource().getComponent();return d&&d.getParent()==this.getComponent()&&this.GetAllowedActions()&b?b:AdfDnDContext.ACTION_NONE};AdfDashboardDropTarget.prototype.NeedsRowKeyCollectionCheck=function(){return!1};
AdfDashboardDropTarget.prototype.DropOnRowKey=function(a,b,d,e,f,g){AdfLogger.LOGGER.fine("Queing Drop Event with desired drop index:",f);AdfAssert.assertString(f);f=parseInt(f);var h=this.getComponent(),k=a.getDragSource(),l=a.getDragSource().getComponent(),l=h.getPeer().getDraggedSourceChildIndex(l,!1);if(f==l)return AdfDnDContext.ACTION_NONE;(new AdfDropEvent(h,k,a.getTransferable(),b,d,e,g,"children",f)).queue();return b};
AdfUIComponents.createComponentClass("AdfRichPanelDashboard",{componentType:"oracle.adf.RichPanelDashboard",propertyKeys:[{name:"dimensionsFrom",type:"String","default":"parent"},{name:"columns",type:"Number","default":3},{name:"rowHeight",type:"String","default":"100px"},"dropListener",{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelDashboardPeer",!1);AdfDhtmlPanelDashboardPeer.InitSubclass=function(){this._INSERT_DELETE_PIXEL_HEIGHT="40";this._PHASE_2_DURATION_FACTOR=this._PHASE_1_DURATION_FACTOR=0.5};AdfDhtmlPanelDashboardPeer.prototype.InitDomElement=function(a,b){var d=a.getProperty("_allowedFlavors"),e=[];null!=d&&0<d.length&&(e=eval(d));a.setDropTarget(new AdfDashboardDropTarget(e))};AdfDhtmlPanelDashboardPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlPanelDashboardPeer.prototype.ResizeNotify=function(a,b,d,e){delete this._cachedChildWidthInPixels;delete this._cachedChildHeightInPixels;this._workaroundForInternetExplorer(d)};AdfDhtmlPanelDashboardPeer.prototype.ComponentRemoved=function(a){null!=this._animator&&this._animator.stop()};
AdfDhtmlPanelDashboardPeer.prototype.DomReplaceNotify=function(a){if(0<a.id.indexOf("optRnd")){if(null!=this._animator){var b=this._animator.stop();this._processingOptimizedChanges&&null!=b&&2==b.length&&this._deleteElements(b[1],!0)}this._processingOptimizedChanges=!0;var d=AdfAgent.AGENT,e=this.__getDataBody(),b=AdfDomUtils.getChildElements(e),f=b.length,g=[],h=0,k,l;for(k=0;k<f;k++)l=AdfDomUtils.getFirstChildElement(b[k]),null==l||"afrPlaceholder"==l.name?(g[k]="placeholder",h++):g[k]="existing";
f=d.getAttribute(a,"afrDel");if(null!=f){f=eval(f);f.sort(AdfDhtmlPanelDashboardPeer._sortAscending);for(k=l=0;k<g.length;k++)"existing"==g[k]&&(AdfDhtmlPanelDashboardPeer._arrayContains(f,l)&&(g[k]="delete"),l++)}l=AdfDomUtils.getChildElements(a);f=l.length;k=parseInt(d.getAttribute(a,"afrIns"));if(0<f&&(isNaN(k)||k!=f))AdfLogger.LOGGER.severe("Error - the panelDashboard was told to expect "+k+" inserted "+(1==k?"child":"children")+" but "+f+" were sent.");if(0!=h||0!=f){h=[];for(k=0;k<f;k++)h.push(parseInt(d.getAttribute(l[k],
"afrIns")));h.sort(AdfDhtmlPanelDashboardPeer._sortAscending);var d=e.ownerDocument,m=l=0;for(k=0;k<g.length;k++)if("delete"!=g[k])if("placeholder"==g[k])AdfDhtmlPanelDashboardPeer._arrayContains(h,l)?(m++,l++):(g.splice(k,1),e.removeChild(b[k]),b=AdfDomUtils.getChildElements(e),k--);else{if(AdfDhtmlPanelDashboardPeer._arrayContains(h,l)){g.splice(k,0,"placeholder");var n=d.createElement("div"),p=n.style;p.position="absolute";p.overflow="hidden";p.width="1px";p.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+
"px";k<b.length?e.insertBefore(n,b[k]):e.appendChild(n);b=AdfDomUtils.getChildElements(e);m++}l++}for(;m<f;)g.push("placeholder"),h=d.createElement("div"),l=h.style,l.position="absolute",l.overflow="hidden",l.width="1px",l.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+"px",k++<b.length?e.insertBefore(h,b[k++]):e.appendChild(h),b=AdfDomUtils.getChildElements(e),m++}e=[];for(k=0;k<g.length;k++)"placeholder"==g[k]&&e.push(b[k]);for(k=0;k<f;k++){d=e[k];for(h=AdfDomUtils.getFirstChildElement(d);h;)d.removeChild(h),
h=AdfDomUtils.getFirstChildElement(d);h=AdfDomUtils.getFirstChildElement(a);l=AdfDomUtils.getFirstChildElement(h);a.removeChild(h);h.removeChild(l);d.appendChild(l)}e=[];for(k=0;k<g.length;k++)"delete"==g[k]&&e.push(b[k]);var p=AdfPage.PAGE.getLocaleContext().isRightToLeft(),q=this.getComponent(),d=q.getColumns(),h=this._getChildWidthInPixels(q);l=this._getChildHeightInPixels(q);var r=0,m=[];if(g.length>b.length)AdfLogger.LOGGER.severe("ERROR - Mismatch among metaData "+g.length+" and dataBodyChildren "+
b.length);else{for(k=n=0;k<g.length;k++){var s=r%d,t=Math.floor(r/d),u=b[k];this._preventDiagonalMovement(u,s,t,d,h,l,p);"delete"==g[k]?t={element:u,properties:{height:AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT,offsetLeft:s*h,offsetTop:t*l}}:(++n,t={element:u,properties:{width:h,offsetLeft:s*h,offsetTop:t*l}});p&&(u.style.left=u.offsetLeft+"px",u.style.right="auto",t.properties.offsetLeft=(d-1-s)*h);m.push(t);r++}k=q.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(m,k,d,l,n);p=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));
p=isNaN(p)?0:Math.round(p*AdfDhtmlPanelDashboardPeer._PHASE_1_DURATION_FACTOR);q=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(k)&&(q=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,p,m,null,AdfDhtmlPanelDashboardPeer._domReplaceNotifyPhase2,[this,e,g,b,d,h,l,f,k,n],q)}}return a};
AdfDhtmlPanelDashboardPeer._domReplaceNotifyPhase2=function(a){var b=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],k=a[6],l=a[7],m=a[8],n=a[9];a=[];var p=0,q=AdfPage.PAGE.getLocaleContext().isRightToLeft(),r;for(r=0;r<e.length;r++){var s=f[r],t;if("delete"==e[r]){if(t={element:s,properties:{width:1}},q){var u=s.offsetLeft;s.style.left=u+"px";s.style.right="auto";t.properties.offsetLeft=u+h}}else u=p%g,t=Math.floor(p/g),b._preventDiagonalMovement(s,u,t,g,h,k,q),t={element:s,properties:{height:k,offsetLeft:u*
h,offsetTop:t*k}},q&&(s.style.left=s.offsetLeft+"px",s.style.right="auto",t.properties.offsetLeft=(g-1-u)*h),p++;a.push(t)}if(1==l&&0==d.length)for(r=f=0;r<e.length;r++)if("placeholder"==e[r]){e=k*Math.floor(f/g);f=b.getDomElement();a.push({element:f,properties:{scrollTop:e}});break}else"delete"!=e[r]&&f++;AdfDhtmlPanelDashboardPeer._adjustShim(a,m,g,k,n);g=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));g=isNaN(g)?0:Math.round(g*AdfDhtmlPanelDashboardPeer._PHASE_2_DURATION_FACTOR);
k=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(m)&&(k=b.getComponent());b._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,g,a,null,AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,[b,d],k)};AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren=function(a){a=AdfRichUIPeer.CreateSubId(a,"shim");return null!=AdfAgent.AGENT.getElementById(a)};
AdfDhtmlPanelDashboardPeer._adjustShim=function(a,b,d,e,f){b=AdfRichUIPeer.CreateSubId(b,"shim");b=AdfAgent.AGENT.getElementById(b);null!=b&&(d=Math.ceil(f/d)*e,null==a?b.style.height=d+"px":a.push({element:b,properties:{height:d}}))};
AdfDhtmlPanelDashboardPeer.prototype.insertChildBehavior=function(a,b,d){var e=this.__getDataBody(),f=AdfDomUtils.getChildElements(e),g=f.length,h=a.getColumns(),k=this._getChildWidthInPixels(a),l=this._getChildHeightInPixels(a);-1==b&&(b=g);var m=b%h,n=Math.floor(b/h),p=e.ownerDocument,q=p.createElement("div"),r=q.style;d=n*l;r.position="absolute";r.top=d+"px";var s=AdfPage.PAGE.getLocaleContext().isRightToLeft();s?(r.right="auto",r.left=(h-1-m)*k+"px"):r.left=m*k+"px";r.overflow="hidden";r.width=
"1px";r.height=AdfDhtmlPanelDashboardPeer._INSERT_DELETE_PIXEL_HEIGHT+"px";b<f.length?e.insertBefore(q,f[b]):e.appendChild(q);f=AdfDomUtils.getChildElements(e);m=p.createElement("div");m.name="afrPlaceholder";n=m.style;n.position="absolute";n.top="2px";n.bottom="2px";n.left="2px";n.right="2px";n.padding="4px";n.borderWidth="1px";n.borderStyle="solid";n.borderColor="#CCCCCC";q.appendChild(m);m.appendChild(p.createTextNode(" "));p=[];p.push({element:q,properties:{width:k}});for(b=1+b;b<=g;b++)m=b%h,
n=Math.floor(b/h),q=f[b],this._preventDiagonalMovement(q,m,n,h,k,l,s),n={element:q,properties:{offsetLeft:m*k,offsetTop:n*l}},s&&(q.style.left=q.offsetLeft+"px",q.style.right="auto",n.properties.offsetLeft=(h-1-m)*k),p.push(n);a=a.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(p,a,h,l,1+g);g=this.getDomElement();p.push({element:g,properties:{scrollTop:d}});d=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-insert-delete-animation-duration"));d=isNaN(d)?0:Math.round(d*
AdfDhtmlPanelDashboardPeer._PHASE_1_DURATION_FACTOR);g=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(a)&&(g=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,d,p,null,AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,[this,null],g)};
AdfDhtmlPanelDashboardPeer.prototype.showDragFeedback=function(a,b,d,e,f,g,h){AdfAssert.assertPrototype(a,AdfDnDContext);AdfAssert.assertStringOrNull(b);AdfAssert.assertNumber(d);AdfAssert.assertStringOrNull(e);f=a.getDragSource().getComponent();a=this.getComponent();f=this.getDraggedSourceChildIndex(f,!0);g=AdfRichUIPeer.CreateSubId(a.getClientId(),"drpt");g=AdfAgent.AGENT.getElementById(g);if(h&&d==AdfDnDContext.ACTION_NONE)AdfDomUtils.removeCSSClassName(g,"p_AFDropTarget"),this._animateReorderPositionTo(a,
f,null);else if(e!=b)if(d=null,null!=b){d=parseInt(b);var k=a.getColumns();b=this._getChildWidthInPixels(a);e=this._getChildHeightInPixels(a);var l=Math.max(0,d%k),m=Math.max(0,Math.floor(d/k));h=l*b;m*=e;AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(h=(k-1-l)*b);k=g.style;k.width=b+"px";k.height=e+"px";k.left=h+4+"px";k.top=m+4+"px";AdfDomUtils.addCSSClassName(g,"p_AFDropTarget");this._animateReorderPositionTo(a,f,d)}else null!=e&&(AdfDomUtils.removeCSSClassName(g,"p_AFDropTarget"),null!=f&&
(null!=this._animator&&this._animator.stop(),AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles([this,null],f,parseInt(e))))};
AdfDhtmlPanelDashboardPeer.prototype.getRowKeyBounds=function(a){if(null==a)return null;var b=this.__getDataBody(),d=AdfDomUtils.getChildElements(b).length;a=parseInt(a);if(a<d){var e=this.getComponent(),f=e.getColumns(),d=a%f,f=Math.floor(a/f);a=this._getChildWidthInPixels(e);var e=this._getChildHeightInPixels(e),d=d*a,f=f*e,g=AdfAgent.AGENT.getElementPageBounds(b);g.left+=d-b.scrollLeft;g.right=g.left+a;g.top+=f-b.scrollTop;g.bottom=g.top+e;return g}return null};
AdfDhtmlPanelDashboardPeer.prototype.getRowKeyAndOrientationFromHints=function(a,b,d){AdfAssert.assertNumber(a);AdfAssert.assertNumber(b);AdfAssert.assert(null!=d);var e=d[AdfStampedDropTarget.HINT_LAST_ROWKEY],f=d[AdfStampedDropTarget.HINT_LAST_ROWKEY_BOUNDS],g=d[AdfStampedDropTarget.HINT_LAST_DROP_ORIENTATION];if(e&&f&&(AdfAssert.assertString(e),AdfAssert.assertObject(f),a>=f.left&&b>=f.top&&a<=f.right&&b<=f.bottom)){d[AdfStampedDropTarget.ROW_KEY]=e;d[AdfStampedDropTarget.DROP_ORIENTATION]=g;return}e=
!0;f=AdfPage.PAGE.getDnDContext();null!=f&&(f=f.getDragSource().getComponent(),g=this.getComponent(),f.getParent()==g&&(e=!1));this._getRowKeyAndOrientationForPosition(a,b,d,e)};
AdfDhtmlPanelDashboardPeer.prototype.getDraggedSourceChildIndex=function(a,b){var d=this.__getDataBody(),d=AdfDomUtils.getChildElements(d),e=d.length,f=a.getClientId();if(!b&&this._draggedSourceClientId==f)return this._draggedSourceIndex;this._draggedSourceClientId=f;for(var g=null,h=0;h<e;h++){var k=AdfDomUtils.getFirstChildElement(d[h]);if(k&&f==AdfAgent.AGENT.getAttribute(k,"id")){g=h;break}}return this._draggedSourceIndex=g};AdfDhtmlPanelDashboardPeer._sortAscending=function(a,b){return a-b};
AdfDhtmlPanelDashboardPeer._arrayContains=function(a,b){var d,e=a.length;for(d=0;d<e;d++)if(a[d]==b)return!0;return!1};
AdfDhtmlPanelDashboardPeer.prototype._getDispayDropIndexFromCoordinates=function(a,b,d,e,f){var g=AdfAgent.AGENT;if(g.pointInElementBounds(this.getDomElement(),d,e)){d=d-document.documentElement.scrollLeft-g.getElementLeft(b)+b.scrollLeft;e=e-g.getElementTop(b)+b.scrollTop;var h=this._getChildWidthInPixels(a),g=this._getChildHeightInPixels(a);a=a.getColumns();d=Math.floor(d/h);AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(d=a-1-d);a=Math.floor(e/g)*a+d;b=AdfDomUtils.getChildElements(b).length;
f||b--;return""+Math.min(b,a)}return null};AdfDhtmlPanelDashboardPeer.prototype._getRowKeyAndOrientationForPosition=function(a,b,d,e){AdfAssert.assertNumber(a);AdfAssert.assertNumber(b);var f=this.__getDataBody();a=this._getDispayDropIndexFromCoordinates(this.getComponent(),f,a,b,e);d[AdfStampedDropTarget.ROW_KEY]=null!=a?a:null;d[AdfStampedDropTarget.DROP_ORIENTATION]=AdfDropEvent.DROP_ORIENTATION_INSIDE};
AdfDhtmlPanelDashboardPeer.prototype.__getDataBody=function(){var a=this.getDomElement(),a=AdfDomUtils.getFirstChildElement(a);AdfAssert.assertDomElement(a);return a};
AdfDhtmlPanelDashboardPeer.prototype._animateReorderPositionTo=function(a,b,d){null!=this._animator&&this._animator.stop();var e=this.__getDataBody(),f=AdfDomUtils.getChildElements(e),g=f.length;if(0!=g){for(var e=[],h=a.getColumns(),k=this._getChildWidthInPixels(a),l=this._getChildHeightInPixels(a),m=null==d,n=0;n<g;n++){var p=f[n],q={};n==b&&(p.style.display=m?"":"none");if(n!=b){var r=n;m||(null!=b&&r>b&&r--,r>=d&&r++);var s=r%h,r=Math.floor(r/h),t=AdfPage.PAGE.getLocaleContext().isRightToLeft();
t?(p.style.left=p.offsetLeft+"px",p.style.right="auto",q.offsetLeft=(h-1-s)*k):q.offsetLeft=s*k;this._preventDiagonalMovement(p,s,r,h,k,l,t);q.offsetTop=r*l}e[n]={element:p,properties:q}}var u,v;a=a.getClientId();null==d?(u=AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles,v=[this,null]):null==b&&AdfDhtmlPanelDashboardPeer._adjustShim(e,a,h,l,g+1);b=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelDashboard-tr-reorder-animation-duration"));isNaN(b)&&(b=0);d=null;AdfDhtmlPanelDashboardPeer._isDimensionsFromChildren(a)&&
(d=this.getComponent());this._animator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,b,e,null,u,v,d)}};AdfDhtmlPanelDashboardPeer.prototype._preventDiagonalMovement=function(a,b,d,e,f,g,h){g*=d;a.offsetTop!=g&&(d=a.style,d.top=g+"px",b>=Math.floor(e/2)?h?(a.style.right="auto",d.left=-f+"px"):d.left=e*f+"px":h?(a.style.right="auto",d.left=e*f+"px"):d.left=-f+"px")};
AdfDhtmlPanelDashboardPeer.prototype._getChildWidthInPixels=function(a){var b=this.__getDataBody(),d=AdfDomUtils.getChildElements(b).length;if(this._cachedChildWidthInPixels&&d==this._cachedChildCount)return this._cachedChildWidthInPixels;a=a.getColumns();this._cachedChildWidthInPixels=Math.floor(b.offsetWidth/a);this._cachedChildCount=d;return this._cachedChildWidthInPixels};
AdfDhtmlPanelDashboardPeer.prototype._getChildHeightInPixels=function(a){if(this._cachedChildHeightInPixels)return this._cachedChildHeightInPixels;a=a.getRowHeight();var b=a.replace(/[0-9]/g,"");if("px"==b)a=parseInt(a.substring(0,a.length-b.length));else if(a=this.__getDataBody(),a=AdfDomUtils.getChildElements(a),0<a.length)a=a[0].offsetHeight;else return 20;return this._cachedChildHeightInPixels=a};
AdfDhtmlPanelDashboardPeer.prototype._deleteElements=function(a,b){if(null!=a){var d=this.__getDataBody(),e;for(e=0;e<a.length;e++){var f=a[e];b||(AdfPage.PAGE.removeComponentsInSubtree(f),AdfAgent.AGENT.elementsRemoved(f));d.removeChild(f)}}};
AdfDhtmlPanelDashboardPeer._resetChildrenPositioningStyles=function(a,b,d){var e=a[0];if(e.getDomElement()){e._deleteElements(a[1],!1);var f=e.__getDataBody();null!=b&&b!=d&&(a=AdfDomUtils.getChildElements(f),b=a[b],f.removeChild(b),a=AdfDomUtils.getChildElements(f),d<a.length?f.insertBefore(b,a[d]):f.appendChild(b),b.style.display="");a=AdfDomUtils.getChildElements(f);d=a.length;e=e.getComponent();b=e.getColumns();var f=e.getRowHeight(),g=f.replace(/[0-9]/g,""),h=f.substring(0,f.length-g.length),
h=parseFloat(h),k=AdfDhtmlPanelDashboardPeer._formatPercent(1/b);for(i=0;i<d;i++){var l=AdfDhtmlPanelDashboardPeer._formatPercent(i%b/b),m=a[i].style;m.top=h*Math.floor(i/b)+g;AdfPage.PAGE.getLocaleContext().isRightToLeft()?(m.left="auto",m.right=l):m.left=l;m.height=f;m.width=k}a=e.getClientId();AdfDhtmlPanelDashboardPeer._adjustShim(null,a,b,h,d);this._processingOptimizedChanges=!1;AdfPage.PAGE.doResizeNotify(e)}};
AdfDhtmlPanelDashboardPeer._formatPercent=function(a){a=""+100*a;var b=a.length,d=a.indexOf(".");-1!=d&&d<b-2&&(a=a.substring(0,d+3));return a+"%"};
AdfDhtmlPanelDashboardPeer.prototype._workaroundForInternetExplorer=function(a){if(AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM){var b=this.getDomElement(),d=b.scrollWidth;null==a&&(a=b.offsetWidth);d>a&&(b=this.__getDataBody(),AdfDhtmlPanelDashboardPeer._scrollBarWidth||(AdfDhtmlPanelDashboardPeer._scrollBarWidth=d-a+2+"px"),AdfPage.PAGE.getLocaleContext().isRightToLeft()||(b.style.right=AdfDhtmlPanelDashboardPeer._scrollBarWidth))}};
function AdfPanelDashboardBehavior(a,b,d){this.Init(a,b,d)}AdfObject.createSubclass(AdfPanelDashboardBehavior,AdfClientBehavior);AdfPanelDashboardBehavior.prototype.Init=function(a,b,d,e){AdfPanelDashboardBehavior.superclass.Init.call(this);AdfAssert.assertString(a);this._panelDashboardId=a;this._type=b;this._index=d;this._alignId=e};
AdfPanelDashboardBehavior.prototype.initialize=function(a){AdfAssert.assertPrototype(a,AdfUIComponent);a instanceof AdfUICommand&&a.addEventListener(AdfActionEvent.ACTION_EVENT_TYPE,this._actionHandler,this)};
AdfPanelDashboardBehavior.prototype._actionHandler=function(a){if(a.isPartial()){var b=a.getSource();a=b.findComponent(this._panelDashboardId);AdfAssert.assert(null!=a,'AdfUIComponent.findComponent() found no results; the panelDashboard referenced by the panelDashboardBehavior for\x3d"'+this._panelDashboardId+'" could not be found (panelDashboard component \x3d '+a+").");if(null!=a){var d=parseInt(this._index);isNaN(d)&&(d=-1);var e=b;null!=this._alignId&&(e=b.findComponent(this._alignId),AdfAssert.assertPrototype(e,
AdfUIComponent,'The align component referenced by the panelDashboardBehavior for\x3d"'+this._panelDashboardId+'" and alignId\x3d"'+this._alignId+'" could not be found (behaviorComponent clientId \x3d '+b.getClientId()+")."));b=a.getPeer();AdfAssert.assert(null!=b.insertChildBehavior,'The panelDashboard referenced by the panelDashboardBehavior for\x3d"'+this._panelDashboardId+'" is not a panelDashboard (panelDashboard component \x3d '+a+").");b.insertChildBehavior(a,d,e)}}};
AdfUIComponents.createComponentClass("AdfRichDecorativeBox",{componentType:"oracle.adf.RichDecorativeBox",propertyKeys:[{name:"topHeight",type:"String","default":"50px"},{name:"topLandmark",type:"String","default":"none"},{name:"centerLandmark",type:"String","default":"none"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"theme",type:"String"},{name:"dimensionsFrom",
type:"String","default":"parent"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlDecorativeBoxPeer",!1);AdfDhtmlDecorativeBoxPeer.prototype.needsChildVisibilityChanges=function(a){return!0};AdfDhtmlDecorativeBoxPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlDecorativeBoxPeer.prototype.BindToComponent=function(a,b){AdfDhtmlDecorativeBoxPeer.superclass.BindToComponent.call(this,a,b);var d=a.getClientId(),e=AdfAgent.AGENT;this._topLeftElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"tl"));this._topElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"t"));this._topInnerElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"t-i"));this._topRightElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"tr"));this._leftElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,
"l"));this._centerElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"c"));this._rightElement=e.getElementById(AdfRichUIPeer.CreateSubId(d,"r"));if(this._isFlowLayout=AdfDomUtils.containsCSSClassName(b,"p_AFFlow"))this._topWrapperElement=AdfDomUtils.getFirstChildElement(b)};
AdfDhtmlDecorativeBoxPeer.prototype.UnbindFromComponent=function(){AdfDhtmlDecorativeBoxPeer.superclass.UnbindFromComponent.call(this);this._rightElement=this._centerElement=this._leftElement=this._topRightElement=this._topInnerElement=this._topElement=this._topLeftElement=null};AdfDhtmlDecorativeBoxPeer.prototype.ResizeNotify=function(a,b,d,e){};
AdfDhtmlDecorativeBoxPeer.prototype.DomReplaceNotify=function(a){if(a.parentNode!=this._topInnerElement)return a;var b=AdfAgent.AGENT,d=!1,e=AdfDomUtils.isVisible(this._topInnerElement),f=AdfDomUtils.isVisible(a);f!=e&&(AdfDomUtils.setVisible(this._topInnerElement,f),this._repositionPanes(),d=!0);b.prepareStretchedChild(a,"0px");return!d?(b.resizeStretchedChild(a,"0px"),a):this.getDomElement()};
AdfDhtmlDecorativeBoxPeer.prototype.ChildVisibilityChanged=function(a,b,d){if(b.parentNode!=this._topInnerElement)return!1;AdfDomUtils.setVisible(this._topInnerElement,d);this._repositionPanes();AdfDomUtils.setVisible(b,d);AdfPage.PAGE.doResizeNotify(this.getComponent());return!0};
AdfDhtmlDecorativeBoxPeer.prototype._repositionPanes=function(){var a;a=this._topInnerElement&&AdfDomUtils.isVisible(this._topInnerElement)?this.getComponent().getTopHeight():this._getAreaSkinProperty(this._topElement,"height");this._topLeftElement&&(this._topLeftElement.style.height=a);this._topElement&&(this._topElement.style.height=a);this._topRightElement&&(this._topRightElement.style.height=a);this._isFlowLayout?(this._topElement.parentNode.style.height=a,this._isTopStretched()&&(this._topWrapperElement.style.height=
a)):(this._leftElement&&(this._leftElement.style.top=a),this._centerElement&&(this._centerElement.style.top=a),this._rightElement&&(this._rightElement.style.top=a))};AdfDhtmlDecorativeBoxPeer.prototype._isTopStretched=function(){return this._isFlowLayout?this._topInnerElement&&this._topInnerElement.parentNode==this._topWrapperElement:this._topInnerElement&&this._topInnerElement.parentNode==this.getDomElement()};
AdfDhtmlDecorativeBoxPeer.prototype._getAreaSkinProperty=function(a,b){var d=this.getComponent().getTheme(),e=AdfPage.PAGE.getLookAndFeel(),f=AdfPage.PAGE.getLocaleContext().isRightToLeft();switch(a){case this._topLeftElement:area=f?"top-end":"top-start";break;case this._topElement:case this._topInnerElement:area="top";break;case this._topRightElement:area=f?"top-start":"top-end";break;default:return null}f=null;null!=d&&(f=e.getSkinProperty("af|decorativeBox::"+area+"[theme\x3d'"+d+"']-tr-"+b));
null==f&&(f=e.getSkinProperty("af|decorativeBox::"+area+"-tr-"+b));return f};AdfDhtmlDecorativeBoxPeer.prototype.getContainerId=function(a){return"simple"==AdfPage.PAGE.getLookAndFeel().getSkinProperty("BORDER_STYLE")?AdfRichUIPeer.createSubId(this.getComponent().getClientId(),"c"):this.getComponent().getClientId()};
AdfUIComponents.createComponentClass("AdfRichPanelSplitter",{componentType:"oracle.adf.RichPanelSplitter",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"dimensionsFrom",type:"String","default":"parent"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"orientation",
type:"String","default":"horizontal"},{name:"positionedFromEnd",type:"Boolean","default":!1},{name:"splitterPosition",type:"Number","default":200},{name:"collapsed",type:"Boolean","default":!1},{name:"firstBorder",type:"String","default":"skin"},{name:"secondBorder",type:"String","default":"skin"},{name:"firstLandmark",type:"String","default":"none"},{name:"secondLandmark",type:"String","default":"none"}],superclass:AdfUIPanel});
AdfRichPanelSplitter.HORIZONTAL_SPLIT="horizontal";AdfRichPanelSplitter.VERTICAL_SPLIT="vertical";
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelSplitterBasePeer",!1);
AdfDhtmlPanelSplitterBasePeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelSplitter.SPLITTER_POSITION,AdfRichPanelSplitter.COLLAPSED);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE);this._DIVIDER_WIDTH=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelSplitter-tr-divider-size"),10);this._SPLITTER_PADDING_PIXELS="0px";this._MINIMUM_PANE_SIZE=0;this._PANEL_SPLITTER_COLLAPSE_ANIMATION_DURATION="af|panelSplitter-tr-collapse-animation-duration";
this._DISCLOSED_STATE="p_AFDisclosed";this._COLLAPSE_KEY="af_panelSplitter.TIP_COLLAPSE";this._RESTORE_KEY="af_panelSplitter.TIP_RESTORE";this._COLLAPSE_LABELED_SECTION_KEY="af_panelSplitter.TIP_COLLAPSE_LABELED_PANE";this._RESTORE_LABELED_SECTION_KEY="af_panelSplitter.TIP_RESTORE_LABELED_PANE"};
AdfDhtmlPanelSplitterBasePeer.prototype.BindToComponent=function(a,b){AdfDhtmlPanelSplitterBasePeer.superclass.BindToComponent.call(this,a,b);var d=a.getClientId(),e=AdfRichUIPeer.CreateSubId(d,"f"),f=AdfRichUIPeer.CreateSubId(d,"s"),g=AdfRichUIPeer.CreateSubId(d,"d"),h=AdfRichUIPeer.CreateSubId(d,"h"),d=AdfRichUIPeer.CreateSubId(d,"i"),k=AdfAgent.AGENT;this._firstDom=k.getElementById(e);this._secondDom=k.getElementById(f);this._dividerDom=k.getElementById(g);this._highlighterDom=k.getElementById(h);
this._iconDom=k.getElementById(d)};AdfDhtmlPanelSplitterBasePeer.prototype.ComponentSplitterPositionChanged=function(a,b,d,e){AdfPage.PAGE.doResizeNotify(a)};AdfDhtmlPanelSplitterBasePeer.prototype.ComponentCollapsedChanged=function(a,b,d,e){b=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a);this._dividerDom.style.cursor=d?"default":"";this._handleCollapseAnimation(d,a,b)};AdfDhtmlPanelSplitterBasePeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlPanelSplitterBasePeer.prototype.needsChildVisibilityChanges=function(a){return!0};
AdfDhtmlPanelSplitterBasePeer.prototype.ResizeNotify=function(a,b,d,e){if(!this._collapseAnimator){var f=this.getComponent(),g=this._firstDom,h=this._secondDom,k=this._dividerDom,l=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(f),m=this._isDimensionsFromParent(),n=AdfDhtmlPanelSplitterBasePeer._isChildVisible(g),p=AdfDhtmlPanelSplitterBasePeer._isChildVisible(h),q=f.getCollapsed(),r=q?0:parseInt(f.getSplitterPosition(),10),f=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(f);if(!m&&l)q||(f?null!=
h&&(h.style.width=r+"px"):null!=g&&(g.style.width=r+"px"));else if(!(!1==n&&!1==p)){a=a!=d;b=b!=e;var s=!(a||b);m?n!=p?this._resizeOnly(n?g:h,d,e,a,b):(f?(n=h,p=g):(n=g,p=h),(l?this._resizeHorizontal:this._resizeVertical).call(this,n,p,k,d,e,r,a,b,s,AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH,f),d=AdfDomUtils.getFirstChildElement(g),h=AdfDomUtils.getFirstChildElement(h),g=this._getPanePadding(g),r=AdfAgent.AGENT,r.resizeStretchedChild(d,g),r.resizeStretchedChild(h,g)):(e=!f,k=null,e&&p&&(k=g),!e&&
n&&(k=h),null!=k&&this._resizeOnly(k,d,r,a,!1),n&&(p&&!q)&&(f?h.style.height=r+"px":g.style.height=r+"px"))}}};
AdfDhtmlPanelSplitterBasePeer.prototype.DomReplaceNotify=function(a){var b=a.parentNode;if(b==this._firstDom||b==this._secondDom){var d=this.getComponent(),e=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(d);if(!this._isDimensionsFromParent()){if(e)return a;d=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(d);if(b==this._firstDom&&d||b==this._secondDom&&!d)return a}var d=!1,e=AdfDomUtils.isVisible(b),f=AdfDomUtils.isVisible(a);f!=e&&(b!=this._getCollapsedPane()&&AdfDomUtils.setVisible(b,f),this._repositionPanes(),
d=!0);b=this._getPanePadding(b);e=AdfAgent.AGENT;e.prepareStretchedChild(a,b);return!d?(e.resizeStretchedChild(a,b),a):this.getDomElement()}return a};AdfDhtmlPanelSplitterBasePeer.prototype.ChildVisibilityChanged=function(a,b,d){a=b.parentNode;if(a==this._firstDom||a==this._secondDom)return a!=this._getCollapsedPane()&&AdfDomUtils.setVisible(a,d),AdfDomUtils.setVisible(b,d),this._repositionPanes(),AdfPage.PAGE.doResizeNotify(this.getComponent()),!0};
AdfDhtmlPanelSplitterBasePeer.prototype.__handleCollapseRestore=function(a){var b=a.getNativeEventTarget();if(AdfDomUtils.isAncestorOrSelf(this._iconDom,b)){var b=this.getComponent(),d=b.getCollapsed();b.setProperty(AdfRichPanelSplitter.COLLAPSED,!d,!0);AdfAgent.AGENT.eatEvent(a.getNativeEvent());return!0}return!1};AdfDhtmlPanelSplitterBasePeer.prototype.__isDragging=function(){return this._dragging};
AdfDhtmlPanelSplitterBasePeer.prototype.__startDrag=function(a){AdfDomUtils.setVisible(this._iconDom,!1);a=a.getNativeEvent();this._dragging=!0;AdfPage.PAGE.startDrag(a,this.createCallback(this._handleDrag),this.createCallback(this._handleDrop),void 0,!0)};AdfDhtmlPanelSplitterBasePeer.prototype.__isEventInDivider=function(a,b){var d=a.getNativeEventTarget();return AdfDomUtils.isAncestorOrSelf(this._dividerDom,d)&&(b||!AdfDomUtils.isAncestorOrSelf(this._iconDom,d))};
AdfDhtmlPanelSplitterBasePeer.prototype.__setHighlighterVisibility=function(a){AdfDomUtils.setVisible(this._highlighterDom,a)};
AdfDhtmlPanelSplitterBasePeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()){var b=this.getComponent(),d=a.getNativeEventTarget(),e=a.getKeyCode();if(e==AdfKeyStroke.P_KEY){var f=a.getNativeEvent();f.ctrlKey&&f.altKey&&(this._handleSplitterNavigationEvent(a),a.cancel())}if(!b.getCollapsed()&&AdfDomUtils.isAncestorOrSelf(this._iconDom,d)){var d=parseInt(b.getSplitterPosition(),10),f=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(b),g=0;if(e==AdfKeyStroke.ARROWUP_KEY&&!f||e==AdfKeyStroke.ARROWLEFT_KEY&&
f)g=-5;else if(e==AdfKeyStroke.ARROWDOWN_KEY&&!f||e==AdfKeyStroke.ARROWRIGHT_KEY&&f)g=5;if(0!=g){AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(b)&&(g=-g);var e=this._isDimensionsFromParent(),h=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(b),e=this._getConstrainedSplitterPos(b,f,d+g,!e&&!f&&!h);b.setProperty(AdfRichPanelSplitter.SPLITTER_POSITION,e,!0);a.cancel()}}}};
AdfDhtmlPanelSplitterBasePeer.prototype._handleCollapseAnimation=function(a,b,d){var e=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(b),f=d?this._secondDom:this._firstDom,g=AdfDomUtils.getFirstChildElement(f),h=d?this._firstDom:this._secondDom,k=a?0:parseInt(b.getSplitterPosition(),10),l=parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty(AdfDhtmlPanelSplitterBasePeer._PANEL_SPLITTER_COLLAPSE_ANIMATION_DURATION),10);isNaN(l)&&(l=0);this._isDimensionsFromParent()?this._handleDimensionsFromParentCollapseAnimation(a,
b,d,e,f,g,h,k,l):this._handleDimensionsFromChildrenCollapseAnimation(a,b,d,e,f,g,h,k,l)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDimensionsFromChildrenCollapseAnimation=function(a,b,d,e,f,g,h,k,l){var m=this,n;n=e?"width":"height";fixedPaneSize=a?0:k;AdfDomUtils.setVisible(f,!0);k={element:f,properties:{}};k.properties[n]=fixedPaneSize;this._collapseAnimator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,l,[k],null,function(k){m._afterCollapseAnimation(a,e,b,d,f,g,h,null,!1)},[],b)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDimensionsFromParentCollapseAnimation=function(a,b,d,e,f,g,h,k,l){var m=this,n,p=null==g?null:g.style,q=AdfDomUtils.getFirstChildElement(h),r=null==q?null:q.style,s=AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH,t,u,v,w=this.getDomElement(),y=e?w.clientWidth:w.clientHeight,z=this._dividerDom,A=h.style;a?(t=0,v=y-s+1):(t=k+1,v=y-k-s+1);e?(n="width",u="right"):(n="height",u="bottom");y=d?y-k-s:k;a?e?(null!=p&&(p.width=this._getStyleWidth(g)+"px"),null!=r&&
(r.width=w.clientWidth-s+1+"px"),A.width=this._getStyleWidth(h)+"px"):(null!=p&&(p.height=this._getStyleHeight(g)+"px"),null!=r&&(r.height=w.clientHeight-s+1+"px"),A.height=this._getStyleHeight(h)+"px"):e?(null!=p&&(p.width=k+1+"px"),null!=r&&(r.width=this._getStyleWidth(q)+"px"),A.width=w.clientWidth-s+1+"px"):(null!=p&&(p.height=k+1+"px"),null!=r&&(r.height=this._getStyleHeight(q)+"px"),A.height=w.clientHeight-s+1+"px");null!=p&&(p[u]="");null!=r&&(r[u]="");A[u]="";d&&(k=z.style,e?(k.left=z.offsetLeft+
"px",k.right=""):(k.top=z.offsetTop+"px",k.bottom=""));AdfDomUtils.setVisible(f,!0);k=[];p={element:f,properties:{}};p.properties[n]=t;k.push(p);p={element:h,properties:{}};p.properties[n]=v;d||(p.properties[e?"offsetLeft":"offsetTop"]=y+s-1);k.push(p);p={element:z,properties:{}};p.properties[e?"offsetLeft":"offsetTop"]=y;k.push(p);this._collapseAnimator=AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,l,k,null,function(k){m._afterCollapseAnimation(a,e,b,d,f,g,h,
q,!0)},[],null)};
AdfDhtmlPanelSplitterBasePeer.prototype._afterCollapseAnimation=function(a,b,d,e,f,g,h,k,l){delete this._collapseAnimator;AdfDomUtils.setVisible(f,!a);f=AdfAgent.AGENT;(l||!b)&&null!=g&&f.prepareStretchedChild(g,"0px");l&&null!=k&&f.prepareStretchedChild(k,"0px");l&&!e&&(h.style[b?"right":"bottom"]="0px");AdfDomUtils.setVisible(this._highlighterDom,!1);this._updateDivider(a,e);l&&(h.style[b?"width":"height"]="");l&&e&&(this._dividerDom.style[b?"left":"top"]="");!l&&b&&f.getPlatform()==AdfAgent.IE_PLATFORM&&
(a=f.getVersion(),7<a&&9>a&&(a=this.getDomElement(),a.style.display="none",AdfPage.PAGE.scheduleTimer(this,this._afterTheAfterCollapseAnimationForIe,[a],1)));AdfPage.PAGE.doResizeNotify(d)};AdfDhtmlPanelSplitterBasePeer.prototype._afterTheAfterCollapseAnimationForIe=function(a){a[0].style.display="";this._iconDom.focus()};
AdfDhtmlPanelSplitterBasePeer.prototype._getStyleHeight=function(a){var b=AdfAgent.AGENT.getComputedStyle(a);return a.offsetHeight-AdfAgent.getCSSLengthAsInt(b.borderTopWidth)-AdfAgent.getCSSLengthAsInt(b.borderBottomWidth)-AdfAgent.getCSSLengthAsInt(b.paddingTop)-AdfAgent.getCSSLengthAsInt(b.paddingBottom)};
AdfDhtmlPanelSplitterBasePeer.prototype._getStyleWidth=function(a){var b=AdfAgent.AGENT.getComputedStyle(a);return a.offsetWidth-AdfAgent.getCSSLengthAsInt(b.borderLeftWidth)-AdfAgent.getCSSLengthAsInt(b.borderRightWidth)-AdfAgent.getCSSLengthAsInt(b.paddingLeft)-AdfAgent.getCSSLengthAsInt(b.paddingRight)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleSplitterNavigationEvent=function(a){var b=a.getNativeEventTarget(),d=AdfRichUIPeer.getFirstAncestorComponent(b);d&&d instanceof AdfRichPanelSplitter?(d=d.getPeer(),AdfDomUtils.isAncestorOrSelf(d._iconDom,b)?(d=d._secondDom,b=!1):(d=document.body,b=!0)):(d=document.body,b=!0);d=this._findNextSplitter(d);!d&&!b&&(d=this._findNextSplitter(document.body));d&&(d.focus(),a.cancel())};
AdfDhtmlPanelSplitterBasePeer.prototype._findNextSplitter=function(a){for(var b=AdfDomUtils.isVisible,d=AdfAgent.AGENT.isElementHTML,e=AdfRichUIPeer.getFirstAncestorComponent,f=/::i$/;;){if(a.hasChildNodes()&&b(a))a=a.firstChild;else for(;;){var g=a;a=g.nextSibling;if(null==a){if(a=g.parentNode,null==a)return null}else break}var h,k;if(1==a.nodeType&&d(a)&&b(a)&&"A"==a.nodeName&&a.id&&f.test(a.id)&&(h=e(a))&&h instanceof AdfRichPanelSplitter&&(k=h.getPeer())&&k._iconDom==a)return k._iconDom}};
AdfDhtmlPanelSplitterBasePeer.prototype._getConstrainedSplitterPos=function(a,b,d,e){a=this.getDomElement();b=(b?a.clientWidth:a.clientHeight)-AdfDhtmlPanelSplitterBasePeer._DIVIDER_WIDTH-AdfDhtmlPanelSplitterBasePeer._MINIMUM_PANE_SIZE;d=Math.max(d,AdfDhtmlPanelSplitterBasePeer._MINIMUM_PANE_SIZE);e||(d=Math.min(d,b));return d};AdfDhtmlPanelSplitterBasePeer.prototype._getPanePadding=function(a){a=a.style.paddingTop;""==a&&(a="0px");return a};
AdfDhtmlPanelSplitterBasePeer.prototype._handleTouchMovement=function(a,b){this._handleDrag(null,a,b);this._handleDrop(null,a,b)};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDrag=function(a,b,d){var e;a=this.getComponent();var f=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a),g=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(a),h=null;if(g){if(0==b)return;d=b;b=f?"right":"left"}else{if(0==d)return;b=f?"bottom":"top"}var k=this._isDimensionsFromParent();if(k)h=this._dividerDom.style;else if(null==this._flowDividerDom){var h=AdfAgent.AGENT,l=this._highlighterDom.cloneNode(!0);e=l.ownerDocument.createElement("div");e.className=
this._dividerDom.className;var m=this._dividerDom.offsetHeight,n=e.style;n.position="absolute";n.height=m+"px";g?n.width=this._dividerDom.style.width:(n.left="0px",n.right="0px");e.appendChild(l);h.disableUserSelect(e);this._highlighterDom.style.visibility="hidden";h.removeIdsFromDomSubTree(e);h=e.style;!g&&f?(b="top",h[b]=this._firstDom.offsetHeight+"px"):(l=a.getCollapsed()?0:parseInt(a.getSplitterPosition(),10),h[b]=l+"px");l=this.getDomElement();l.insertBefore(e,l.firstChild);this._flowDividerDom=
e}else!g&&f&&(b="top"),AdfDomUtils.setVisible(this._flowDividerDom,!0),h=this._flowDividerDom.style;e=parseInt(h[b],10);!k&&!g&&f?(d=e+d,f=(a.getCollapsed()?0:parseInt(a.getSplitterPosition(),10))+this._firstDom.offsetHeight,a=this._getConstrainedSplitterPos(a,g,f-d,!1),h[b]=f-a+"px"):(a=this._getConstrainedSplitterPos(a,g,f?e-d:e+d,!k&&!g&&!f),h[b]=a+"px")};
AdfDhtmlPanelSplitterBasePeer.prototype._handleDrop=function(a,b,d){this._dragging=!1;AdfDomUtils.setVisible(this._iconDom,!0);a=this.getComponent();d=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a);var e=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(a),f=this._isDimensionsFromParent();b=e?d?"right":"left":d?"bottom":"top";var g;if(f)g=this._dividerDom.style;else if(null!=this._flowDividerDom)g=this._flowDividerDom.style,AdfDomUtils.setVisible(this._flowDividerDom,!1);else return;!f&&!e&&d?
(b=parseInt(g.top,10),b=(a.getCollapsed()?0:parseInt(a.getSplitterPosition(),10))+this._firstDom.offsetHeight-b):b=parseInt(g[b],10);null!=this._flowDividerDom&&(this._highlighterDom.style.visibility="visible",this._flowDividerDom.parentNode.removeChild(this._flowDividerDom),this._flowDividerDom=null);a.setProperty(AdfRichPanelSplitter.SPLITTER_POSITION,b,!0)};
AdfDhtmlPanelSplitterBasePeer.prototype._repositionPanes=function(){var a=AdfAgent.AGENT,b=this._firstDom,d=this._secondDom,e=this._dividerDom,f=AdfDhtmlPanelSplitterBasePeer._isChildVisible(b),g=AdfDhtmlPanelSplitterBasePeer._isChildVisible(d);AdfDomUtils.setVisible(e,f&&g);this._isDimensionsFromParent()&&(f!=g?(e=AdfDhtmlPanelSplitterBasePeer._SPLITTER_PADDING_PIXELS,a.repositionStretchedElement(f?b:d,e,e,e,e)):(e=this.getComponent(),f=AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(e),e=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(e),
a.removeStyleProperty(f?d:b,e?f?"left":"right":f?"top":"bottom")))};AdfDhtmlPanelSplitterBasePeer.prototype._resizeHorizontal=function(a,b,d,e,f,g,h,k,l,m,n){var p=AdfAgent.AGENT;l&&(p.setOuterWidth(a,g+1),n=n?"right":"left",d.style[n]=g+"px",b.style[n]=g+m-1+"px");if(l||h)e=Math.max(0,e-g-m),p.resizeStretchedElement(b,e);k&&(p.resizeStretchedElement(a,void 0,f),p.resizeStretchedElement(b,void 0,f),p.resizeStretchedElement(d,void 0,f))};
AdfDhtmlPanelSplitterBasePeer.prototype._resizeVertical=function(a,b,d,e,f,g,h,k,l,m,n){var p=AdfAgent.AGENT;l&&(p.setOuterHeight(a,g+1),n=n?"bottom":"top",d.style[n]=g+"px",b.style[n]=g+m-1+"px");if(l||k)f=Math.max(0,f-g-m),p.resizeStretchedElement(b,void 0,f);h&&(p.resizeStretchedElement(a,e,void 0),p.resizeStretchedElement(b,e,void 0),p.resizeStretchedElement(d,e,void 0))};
AdfDhtmlPanelSplitterBasePeer.prototype._resizeOnly=function(a,b,d,e,f){e=AdfAgent.AGENT;e.resizeStretchedElement(a,b,d);b=AdfDomUtils.getFirstChildElement(a);a=this._getPanePadding(a);e.resizeStretchedChild(b,a)};AdfDhtmlPanelSplitterBasePeer.prototype._getCollapsedPane=function(){var a=this.getComponent();return a.getCollapsed()?AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd(a)?this._secondDom:this._firstDom:null};
AdfDhtmlPanelSplitterBasePeer.prototype._updateDivider=function(a,b){var d,e=this.getComponent();d=AdfDhtmlPanelSplitterBasePeer.__isHorizontal(e)?b?a?"af|panelSplitter::horizontal-collapse-icon":"af|panelSplitter::horizontal-restore-icon":a?"af|panelSplitter::horizontal-restore-icon":"af|panelSplitter::horizontal-collapse-icon":b?a?"af|panelSplitter::vertical-collapse-icon":"af|panelSplitter::vertical-restore-icon":a?"af|panelSplitter::vertical-restore-icon":"af|panelSplitter::vertical-collapse-icon";
AdfDomUtils.addOrRemoveCSSClassName(!a,this._dividerDom,AdfDhtmlPanelSplitterBasePeer._DISCLOSED_STATE);var f=this._iconDom,g=AdfDomUtils.getFirstChildElement(f);AdfDomUtils.swapIcon(g,d);d=AdfDomUtils.getFirstChildElement(f);e=AdfDhtmlPanelSplitterBasePeer._getCollapseIconTooltipText(e,a,b);f.title=e;f.setAttribute("aria-label",e);f.setAttribute("aria-expanded",(!a).toString());"IMG"==d.tagName&&(d.alt=e);d.title=e};
AdfDhtmlPanelSplitterBasePeer.prototype.ComponentRemoved=function(a){this._touchMoveManager&&this._touchMoveManager.unregister();AdfDhtmlPanelSplitterBasePeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlPanelSplitterBasePeer.prototype._isDimensionsFromParent=function(){if(null==this._dimensionsFromParent){var a=null;null!=this._dividerDom?a=AdfAgent.AGENT.getComputedStyle(this._dividerDom):null==a&&null!=this._firstDom?a=AdfAgent.AGENT.getComputedStyle(this._firstDom):null==a&&null!=this._secondDom&&(a=AdfAgent.AGENT.getComputedStyle(this._secondDom));this._dimensionsFromParent="absolute"==a.position}return this._dimensionsFromParent};
AdfDhtmlPanelSplitterBasePeer._isChildVisible=function(a){if(null==a)return!1;a=AdfDomUtils.getFirstChildElement(a);return null==a||AdfDomUtils.isVisible(a)};AdfDhtmlPanelSplitterBasePeer.__isHorizontal=function(a){return a.getOrientation()!=AdfRichPanelSplitter.VERTICAL_SPLIT};AdfDhtmlPanelSplitterBasePeer._getPositionedFromEnd=function(a){var b=a.getPositionedFromEnd();AdfDhtmlPanelSplitterBasePeer.__isHorizontal(a)&&AdfPage.PAGE.getLocaleContext().isRightToLeft()&&(b=!b);return b};
AdfDhtmlPanelSplitterBasePeer._getCollapseIconTooltipText=function(a,b,d){var e=AdfPage.PAGE.getLookAndFeel(),f=a.getFirstLandmark();a=a.getSecondLandmark();if(!d&&"none"!=f)return b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_LABELED_SECTION_KEY:AdfDhtmlPanelSplitterBasePeer._COLLAPSE_LABELED_SECTION_KEY,e.getTranslatedString(b,f);if(d&&"none"!=a)return b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_LABELED_SECTION_KEY:AdfDhtmlPanelSplitterBasePeer._COLLAPSE_LABELED_SECTION_KEY,e.getTranslatedString(b,
a);b=b?AdfDhtmlPanelSplitterBasePeer._RESTORE_KEY:AdfDhtmlPanelSplitterBasePeer._COLLAPSE_KEY;return e.getTranslatedString(b)};
AdfRichUIPeer.createPeerClass(AdfDhtmlPanelSplitterBasePeer,"AdfDhtmlPanelSplitterPeer",!1);AdfDhtmlPanelSplitterPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE)};AdfDhtmlPanelSplitterPeer.prototype.HandleComponentClick=function(a){this.__handleCollapseRestore(a)};
AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseOver=function(a){this.getComponent().getCollapsed()||this.__isEventInDivider(a,!0)&&this.__setHighlighterVisibility(!0)};AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseOut=function(a){this._dragging||this.__isEventInDivider(a,!0)&&this.__setHighlighterVisibility(!1)};
AdfDhtmlPanelSplitterPeer.prototype.HandleComponentMouseDown=function(a){if(!this.getComponent().getCollapsed())return this.__isEventInDivider(a,!1)&&this.__startDrag(a),!1};
AdfUIComponents.createComponentClass("AdfRichPanelStretchLayout",{componentType:"oracle.adf.RichPanelStretchLayout",propertyKeys:[{name:"dimensionsFrom",type:"String","default":"parent"},{name:"topHeight",type:"String","default":"50px"},{name:"bottomHeight",type:"String","default":"50px"},{name:"startWidth",type:"String","default":"50px"},{name:"endWidth",type:"String","default":"50px"},{name:"topLandmark",type:"String","default":"none"},{name:"startLandmark",type:"String","default":"none"},{name:"centerLandmark",
type:"String","default":"none"},{name:"endLandmark",type:"String","default":"none"},{name:"bottomLandmark",type:"String","default":"none"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"theme",type:"String"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelStretchLayoutPeer",!1);AdfDhtmlPanelStretchLayoutPeer.prototype.needsResizeNotify=function(a){return!0};AdfDhtmlPanelStretchLayoutPeer.prototype.needsChildVisibilityChanges=function(a){return!0};AdfDhtmlPanelStretchLayoutPeer.prototype.ComponentRemoved=function(a){AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a)};
AdfDhtmlPanelStretchLayoutPeer.prototype.BindToComponent=function(a,b){AdfDhtmlPanelStretchLayoutPeer.superclass.BindToComponent.call(this,a,b);var d=a.getClientId(),e=AdfRichUIPeer.CreateSubId(d,"c"),f=AdfRichUIPeer.CreateSubId(d,"m"),g=AdfRichUIPeer.CreateSubId(d,"t"),h=AdfRichUIPeer.CreateSubId(d,"b"),k=AdfRichUIPeer.CreateSubId(d,"l"),d=AdfRichUIPeer.CreateSubId(d,"r"),l=AdfAgent.AGENT;this._centerPaneElement=l.getElementById(e);this._middleWrapperElement=l.getElementById(f);this._topPaneElement=
l.getElementById(g);this._bottomPaneElement=l.getElementById(h);this._leftPaneElement=l.getElementById(k);this._rightPaneElement=l.getElementById(d)};AdfDhtmlPanelStretchLayoutPeer.prototype.UnbindFromComponent=function(){AdfDhtmlPanelStretchLayoutPeer.superclass.UnbindFromComponent.call(this);this._rightPaneElement=this._leftPaneElement=this._bottomPaneElement=this._topPaneElement=this._middleWrapperElement=this._centerPaneElement=null};
AdfDhtmlPanelStretchLayoutPeer.prototype.ResizeNotify=function(a,b,d,e){a==d&&b==e&&(b=a=void 0);var f=this.getDomElement(),f=AdfDomUtils.getFirstChildElement(f);if(null!=f){var f=this._isDimensionsFromParent(f),g=this._topPaneElement,h=this._leftPaneElement,k=this._centerPaneElement,l=this._rightPaneElement,m=this._bottomPaneElement,n=this._getSize(g,"height"),p=this._getSize(h,"width"),q=this._getSize(l,"width"),r=this._getSize(m,"height"),s=!1;g&&AdfDomUtils.isVisible(g)&&!n&&(n=g.offsetHeight,
s=!0);h&&AdfDomUtils.isVisible(h)&&(p||(s=!0));k&&AdfDomUtils.isVisible(k)&&!f&&this._isJsFlowLayout()&&(s=!0);l&&AdfDomUtils.isVisible(l)&&(q||(s=!0));m&&AdfDomUtils.isVisible(m)&&!r&&(r=m.offsetHeight,s=!0);s&&(this._repositionPanes(),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(this.getComponent()));p=this._getSize(h,"width");q=this._getSize(l,"width");n=e-(n+r);p=d-(p+q);d!=a&&(this._stretchPane(g,d,void 0),this._stretchPane(m,d,void 0));f&&(e!=b&&(this._stretchPane(h,void 0,n),this._stretchPane(l,
void 0,n)),this._stretchPane(k,p,n))}};
AdfDhtmlPanelStretchLayoutPeer.prototype.DomReplaceNotify=function(a){if(this._isChild(a)){var b=!1,d=a.parentNode,e=AdfDomUtils.isVisible(d),f=AdfDomUtils.isVisible(a);f!=e&&(AdfDomUtils.setVisible(d,f),this._repositionPanes(),b=!0);var e=!0,f=!1,g=this.getDomElement(),h=AdfDomUtils.getFirstChildElement(g);if(null==h)return g;var h=this._isDimensionsFromParent(h),k=d.id;-1!=k.indexOf("::t")||-1!=k.indexOf("::b")?this._getSize(d,"height")||(b=f=!0):-1!=k.indexOf("::r")||-1!=k.indexOf("::l")?h?this._getSize(d,
"width")||(b=f=!0):e=!1:-1!=k.indexOf("::c")&&(h||(e=!1));if(e&&!f){var l="0px",m=AdfAgent.AGENT;m.prepareStretchedChild(a,l)}return e&&!b?(m.resizeStretchedChild(a,l),a):g}return a};AdfDhtmlPanelStretchLayoutPeer.prototype.ChildVisibilityChanged=function(a,b,d){return this._isChild(b)?(AdfDomUtils.setVisible(b.parentNode,d),this._repositionPanes(),AdfDomUtils.setVisible(b,d),AdfPage.PAGE.doResizeNotify(this.getComponent()),!0):!1};
AdfDhtmlPanelStretchLayoutPeer.prototype._isJsFlowLayout=function(){var a=this._middleWrapperElement;return null!=a&&"true"==AdfAgent.AGENT.getAttribute(a,"_afrFlowJs")};AdfDhtmlPanelStretchLayoutPeer.prototype._getSize=function(a,b){return a&&AdfDomUtils.isVisible(a)?AdfAgent.getCSSLengthAsInt(a.style[b]):0};
AdfDhtmlPanelStretchLayoutPeer.prototype._getSizeLength=function(a,b){if(a&&AdfDomUtils.isVisible(a)){var d=a.style[b];if(d)return d;d="offset"+b.charAt(0).toUpperCase()+b.substring(1);return a[d]+"px"}return"0px"};AdfDhtmlPanelStretchLayoutPeer.prototype._isChild=function(a){return a.parentNode.parentNode==this.getDomElement()};
AdfDhtmlPanelStretchLayoutPeer.prototype._repositionPanes=function(){var a=AdfAgent.AGENT,b=this._leftPaneElement,d=this._bottomPaneElement,e=this._rightPaneElement,f=this._centerPaneElement,g=this._getSizeLength(this._topPaneElement,"height"),h=this._getSizeLength(d,"height"),d=this._getSizeLength(b,"width"),k=this._getSizeLength(e,"width"),l=this.getDomElement(),l=AdfDomUtils.getFirstChildElement(l);null!=l&&(this._isDimensionsFromParent(l)?(a.repositionStretchedElement(b,g,h),a.repositionStretchedElement(e,
g,h),a.repositionStretchedElement(f,g,h,d,k)):this._isJsFlowLayout()&&(a=0,null!=f&&(f.style.left=d,f.style.right=k,a=Math.max(a,f.offsetHeight)),null!=b&&(a=Math.max(a,b.offsetHeight)),null!=e&&(a=Math.max(a,e.offsetHeight)),this._middleWrapperElement.style.height=a+"px"))};AdfDhtmlPanelStretchLayoutPeer.prototype._isDimensionsFromParent=function(a){null==this._dimensionsFromParent&&(a=a=AdfAgent.AGENT.getComputedStyle(a),this._dimensionsFromParent="absolute"==a.position);return this._dimensionsFromParent};
AdfDhtmlPanelStretchLayoutPeer.prototype._stretchPane=function(a,b,d){if(a){var e=AdfAgent.AGENT;e.resizeStretchedElement(a,b,d);a=AdfDomUtils.getFirstChildElement(a);e.resizeStretchedChild(a,"0px")}};