let statements={
  getAllIssues :
  {
    statement : `SELECT
    *
FROM
    issues
    `,
    bindings :[],
    qstring : "",
    requireCommit : false
  },


  getAllIssuesByID :{
         statement :`/* Formatted on 07/10/2019 10:12:33 AM (QP5 v5.139.911.3011) */
         SELECT I.ISSUE_ID,
                I.REQUEST_ID,
                I.ISSUE_TITLE,
                I.ISSUE_SUMMARY,
                I.ISSUE_PRIORITY,
                I.ASSIGN_TO,
                I.TARGET_RESOLUTION_DATE,
                I.ACTUAL_RESOLUTION_DATE,
                I.READ_STATUS,
                I.REFERENCE_ID,
                I.REFERENCE_TYPE,
                I.ISSUE_TRACK_ID,
                I.ISSUE_TYPE,
                I.FINAL_RESOLUTION,
                I.PROJECT_ID,
                I.DELETED,
                I.DELETED_BY,
                I.DELETED_DATE,
                I.CREATED_WO,
                I.SUBSIDIARY_ID,
                I.CLASSIFICATION,
                I.CREATION_DATE,
                I.TYPE_ID,
                I.ISSUE_SUB_CLASS,
                I.ISSUE_LOCATION,
                I.SHIFT,
                I.TOOL,
                I.REQUIRE_REPORT,
                I.ISSUE_STATE,
                I.ISSUE_NOTE,
                I.CUSTOM_FIELD_CHAR1,
                I.CUSTOM_FIELD_CHAR2,
                I.CUSTOM_FIELD_CHAR3,
                I.CUSTOM_FIELD_CHAR4,
                I.CUSTOM_FIELD_CHAR5,
                I.CUSTOM_FIELD_NUMBER1,
                I.CUSTOM_FIELD_NUMBER2,
                I.CUSTOM_FIELD_NUMBER3,
                I.CUSTOM_FIELD_NUMBER4,
                I.CUSTOM_FIELD_NUMBER5,
                I.CUSTOM_FIELD_DATE1,
                I.CUSTOM_FIELD_DATE2,
                I.CUSTOM_FIELD_DATE3,
                I.CUSTOM_FIELD_DATE4,
                I.CUSTOM_FIELD_DATE5,
                I.CUSTOM_FIELD_LIST1,
                I.CUSTOM_FIELD_CHAR6,
                I.CUSTOM_FIELD_CHAR7,
                I.CUSTOM_FIELD_CHAR8,
                I.CUSTOM_FIELD_CHAR9,
                I.CUSTOM_FIELD_CHAR10,
                I.CUSTOM_FIELD_CHAR11,
                I.CUSTOM_FIELD_CHAR16,
                I.CUSTOM_FIELD_CHAR17,
                I.CUSTOM_FIELD_CHAR12,
                I.ASSEET_ID,
                (select ASSET_NAME from ASSETS_DEFINITION ad where I.ASSEET_ID = ad.ASSET_ID) asset_name,
                (select lat_degrees from ASSETS_DEFINITION ad where I.ASSEET_ID = ad.ASSET_ID) lat,
                (select lon_degrees from ASSETS_DEFINITION ad where I.ASSEET_ID = ad.ASSET_ID) lon,
                I.CUSTOM_FIELD_CHAR13,
                I.CUSTOM_FIELD_CHAR14,
                I.CUSTOM_FIELD_CHAR15,
                I.CUSTOM_FIELD_CHAR18,
                I.CUSTOM_FIELD_CHAR19,
                I.EMPLOYEE_ID,
                I.CUSTOM_FIELD_CHAR20,
                I.CUSTOM_FIELD_DATE9,
                I.CUSTOM_FIELD_DATE11,
                I.CUSTOM_FIELD_DATE12,
                I.CUSTOM_FIELD_DATE13,
                I.CUSTOM_FIELD_DATE14,
                I.CUSTOM_FIELD_DATE15,
                I.CUSTOM_FIELD_DATE16,
                I.CUSTOM_FIELD_DATE17,
                I.CUSTOM_FIELD_DATE18,
                I.CUSTOM_FIELD_DATE19,
                I.CUSTOM_FIELD_DATE20,
                I.CUSTOM_FIELD_DATE10,
                I.CUSTOM_FIELD_DATE6,
                I.CUSTOM_FIELD_DATE7,
                I.CUSTOM_FIELD_DATE8,
                I.CUSTOM_FIELD_NUMBER6,
                I.CUSTOM_FIELD_NUMBER7,
                I.CUSTOM_FIELD_NUMBER8,
                I.CUSTOM_FIELD_NUMBER9,
                I.CUSTOM_FIELD_NUMBER10,
                I.CUSTOM_FIELD_NUMBER11,
                I.CUSTOM_FIELD_NUMBER12,
                I.CUSTOM_FIELD_NUMBER13,
                I.CUSTOM_FIELD_NUMBER14,
                I.CUSTOM_FIELD_NUMBER15,
                I.CUSTOM_FIELD_NUMBER16,
                I.CUSTOM_FIELD_NUMBER17,
                I.CUSTOM_FIELD_NUMBER18,
                I.CUSTOM_FIELD_NUMBER19,
                I.CUSTOM_FIELD_NUMBER20,
                I.SUB_LOCATION,
                I.FINISH_DATE,
                I.START_DATE,
                I.EXPECT_END_DATE,
                I.PERIOD,
                I.DEPARTMENT_ID,
                I.VIOLATION_ID,
                ( select title_en from violation_group_details v where I.VIOLATION_ID = v.VIOLATION_ID) violation_name,
                I.VIOLATION_GROUP_ID,
                I.VIOLATION_VALUE,
                I.ASSET_GROUP_ID,
                I.PARENT_ISSUE_ID,
                I.CREATED_BY,
                I.JOB_ORDER_ID
           FROM HR.ISSUES I
           where I.ISSUE_ID = :ISSUE_ID
         `,
         bindings :[],
         qstring : "",
         requireCommit : false

  },
  insertIssue: {
        statement: `
        INSERT INTO HR.ISSUES (ISSUE_ID,
          REQUEST_ID,
          ISSUE_TITLE,
          ISSUE_SUMMARY,
          ISSUE_PRIORITY,
          ASSIGN_TO,
          TARGET_RESOLUTION_DATE,
          ACTUAL_RESOLUTION_DATE,
          READ_STATUS,
          REFERENCE_ID,
          REFERENCE_TYPE,
          ISSUE_TRACK_ID,
          ISSUE_TYPE,
          FINAL_RESOLUTION,
          PROJECT_ID,
          DELETED,
          CREATED_WO,
          SUBSIDIARY_ID,
          CLASSIFICATION,
          CREATION_DATE,
          TYPE_ID,
          ISSUE_SUB_CLASS,
          ISSUE_LOCATION,
          SHIFT,
          TOOL,
          REQUIRE_REPORT,
          ISSUE_STATE,
          ISSUE_NOTE,
          CUSTOM_FIELD_CHAR1,
          CUSTOM_FIELD_CHAR2,
          CUSTOM_FIELD_CHAR3,
          CUSTOM_FIELD_CHAR4,
          CUSTOM_FIELD_CHAR5,
          CUSTOM_FIELD_NUMBER1,
          CUSTOM_FIELD_NUMBER2,
          CUSTOM_FIELD_NUMBER3,
          CUSTOM_FIELD_NUMBER4,
          CUSTOM_FIELD_NUMBER5,
          CUSTOM_FIELD_DATE1,
          CUSTOM_FIELD_DATE2,
          CUSTOM_FIELD_DATE3,
          CUSTOM_FIELD_DATE4,
          CUSTOM_FIELD_DATE5,
          CUSTOM_FIELD_LIST1,
          CUSTOM_FIELD_CHAR6,
          CUSTOM_FIELD_CHAR7,
          CUSTOM_FIELD_CHAR8,
          CUSTOM_FIELD_CHAR9,
          CUSTOM_FIELD_CHAR10,
          CUSTOM_FIELD_CHAR11,
          CUSTOM_FIELD_CHAR16,
          CUSTOM_FIELD_CHAR17,
          CUSTOM_FIELD_CHAR12,
          ASSEET_ID,
          CUSTOM_FIELD_CHAR13,
          CUSTOM_FIELD_CHAR14,
          CUSTOM_FIELD_CHAR15,
          CUSTOM_FIELD_CHAR18,
          CUSTOM_FIELD_CHAR19,
          EMPLOYEE_ID,
          CUSTOM_FIELD_CHAR20,
          CUSTOM_FIELD_DATE9,
          CUSTOM_FIELD_DATE11,
          CUSTOM_FIELD_DATE12,
          CUSTOM_FIELD_DATE13,
          CUSTOM_FIELD_DATE14,
          CUSTOM_FIELD_DATE15,
          CUSTOM_FIELD_DATE16,
          CUSTOM_FIELD_DATE17,
          CUSTOM_FIELD_DATE18,
          CUSTOM_FIELD_DATE19,
          CUSTOM_FIELD_DATE20,
          CUSTOM_FIELD_DATE10,
          CUSTOM_FIELD_DATE6,
          CUSTOM_FIELD_DATE7,
          CUSTOM_FIELD_DATE8,
          CUSTOM_FIELD_NUMBER6,
          CUSTOM_FIELD_NUMBER7,
          CUSTOM_FIELD_NUMBER8,
          CUSTOM_FIELD_NUMBER9,
          CUSTOM_FIELD_NUMBER10,
          CUSTOM_FIELD_NUMBER11,
          CUSTOM_FIELD_NUMBER12,
          CUSTOM_FIELD_NUMBER13,
          CUSTOM_FIELD_NUMBER14,
          CUSTOM_FIELD_NUMBER15,
          CUSTOM_FIELD_NUMBER16,
          CUSTOM_FIELD_NUMBER17,
          CUSTOM_FIELD_NUMBER18,
          CUSTOM_FIELD_NUMBER19,
          CUSTOM_FIELD_NUMBER20,
          SUB_LOCATION,
          FINISH_DATE,
          START_DATE,
          EXPECT_END_DATE,
          PERIOD,
          DEPARTMENT_ID,
          VIOLATION_ID,
          VIOLATION_GROUP_ID,
          VIOLATION_VALUE,
          ASSET_GROUP_ID,
          PARENT_ISSUE_ID,
          CREATED_BY,
          JOB_ORDER_ID
) VALUES (
  ISSUE_SEQ.NEXTVAL,
    :REQUEST_ID,
    :ISSUE_TITLE,
    :ISSUE_SUMMARY,
    :ISSUE_PRIORITY,
    :ASSIGN_TO,
    :TARGET_RESOLUTION_DATE,
    :ACTUAL_RESOLUTION_DATE,
    :READ_STATUS,
    :REFERENCE_ID,
    1,
    :ISSUE_TRACK_ID,
    :ISSUE_TYPE,
    :FINAL_RESOLUTION,
    :PROJECT_ID,
    0,
    :CREATED_WO,
    :SUBSIDIARY_ID,
    :CLASSIFICATION,
    sysdate,
    :TYPE_ID,
    :ISSUE_SUB_CLASS,
    :ISSUE_LOCATION,
    :ISSUE_SHIFT,  
    :TOOL,
    :REQUIRE_REPORT,
    :ISSUE_STATE,
    :ISSUE_NOTE,
    :CUSTOM_FIELD_CHAR1,
    :CUSTOM_FIELD_CHAR2,
    :CUSTOM_FIELD_CHAR3,
    :CUSTOM_FIELD_CHAR4,
    :CUSTOM_FIELD_CHAR5,
    :CUSTOM_FIELD_NUMBER1,
    :CUSTOM_FIELD_NUMBER2,
    :CUSTOM_FIELD_NUMBER3,
    :CUSTOM_FIELD_NUMBER4,
    :CUSTOM_FIELD_NUMBER5,
    :CUSTOM_FIELD_DATE1,
    :CUSTOM_FIELD_DATE2,
    :CUSTOM_FIELD_DATE3,
    :CUSTOM_FIELD_DATE4,
    :CUSTOM_FIELD_DATE5,
    :CUSTOM_FIELD_LIST1,
    :CUSTOM_FIELD_CHAR6,
    :CUSTOM_FIELD_CHAR7,
    :CUSTOM_FIELD_CHAR8,
    :CUSTOM_FIELD_CHAR9,
    :CUSTOM_FIELD_CHAR10,
    :CUSTOM_FIELD_CHAR11,
    :CUSTOM_FIELD_CHAR16,
    :CUSTOM_FIELD_CHAR17,
    :CUSTOM_FIELD_CHAR12,
    :ASSEET_ID,
    :CUSTOM_FIELD_CHAR13,
    :CUSTOM_FIELD_CHAR14,
    :CUSTOM_FIELD_CHAR15,
    :CUSTOM_FIELD_CHAR18,
    :CUSTOM_FIELD_CHAR19,
    :EMPLOYEE_ID,
    :CUSTOM_FIELD_CHAR20,
    :CUSTOM_FIELD_DATE9,
    :CUSTOM_FIELD_DATE11,
    :CUSTOM_FIELD_DATE12,
    :CUSTOM_FIELD_DATE13,
    :CUSTOM_FIELD_DATE14,
    :CUSTOM_FIELD_DATE15,
    :CUSTOM_FIELD_DATE16,
    :CUSTOM_FIELD_DATE17,
    :CUSTOM_FIELD_DATE18,
    :CUSTOM_FIELD_DATE19,
    :CUSTOM_FIELD_DATE20,
    :CUSTOM_FIELD_DATE10,
    :CUSTOM_FIELD_DATE6,
    :CUSTOM_FIELD_DATE7,
    :CUSTOM_FIELD_DATE8,
    :CUSTOM_FIELD_NUMBER6,
    :CUSTOM_FIELD_NUMBER7,
    :CUSTOM_FIELD_NUMBER8,
    :CUSTOM_FIELD_NUMBER9,
    :CUSTOM_FIELD_NUMBER10,
    :CUSTOM_FIELD_NUMBER11,
    :CUSTOM_FIELD_NUMBER12,
    :CUSTOM_FIELD_NUMBER13,
    :CUSTOM_FIELD_NUMBER14,
    :CUSTOM_FIELD_NUMBER15,
    :CUSTOM_FIELD_NUMBER16,
    :CUSTOM_FIELD_NUMBER17,
    :CUSTOM_FIELD_NUMBER18,
    :CUSTOM_FIELD_NUMBER19,
    :CUSTOM_FIELD_NUMBER20,
    :SUB_LOCATION,
    :FINISH_DATE,
    :START_DATE,
    :EXPECT_END_DATE,
    :PERIOD,
    :DEPARTMENT_ID,
    :VIOLATION_ID,
    :VIOLATION_GROUP_ID,
    :VIOLATION_VALUE,
    :ASSET_GROUP_ID,
    :PARENT_ISSUE_ID,
    :CREATED_BY,
    :JOB_ORDER_ID
)
RETURN ISSUE_ID, REQUEST_ID, ISSUE_TITLE, ISSUE_SUMMARY, ISSUE_PRIORITY, ASSIGN_TO INTO
:R_ISSUE_ID, :R_REQUEST_ID, :R_ISSUE_TITLE, :R_ISSUE_SUMMARY, :R_ISSUE_PRIORITY, :R_ASSIGN_TO `,
returns : ["R_ISSUE_ID","R_REQUEST_ID","R_ISSUE_TITLE","R_ISSUE_SUMMARY","R_ISSUE_PRIORITY","R_ASSIGN_TO"],
bindings: [],
qstring: "",
requireCommit: true
    },
//////////////////////////////////


            insertNIssue: {
              statement: `
              INSERT INTO HR.ISSUES (ISSUE_ID,
                REQUEST_ID,
                ISSUE_TITLE,
                ISSUE_SUMMARY,
                ISSUE_PRIORITY,
                ASSIGN_TO,
                TARGET_RESOLUTION_DATE,
                ACTUAL_RESOLUTION_DATE,
                READ_STATUS,
                REFERENCE_ID,
                REFERENCE_TYPE,
                ISSUE_TRACK_ID,
                ISSUE_TYPE,
                FINAL_RESOLUTION,
                PROJECT_ID,
                DELETED,
                CREATED_WO,
                SUBSIDIARY_ID,
                CLASSIFICATION,
                CREATION_DATE,
                TYPE_ID,
                ISSUE_SUB_CLASS,
                ISSUE_LOCATION,
                SHIFT,
                TOOL,
                REQUIRE_REPORT,
                ISSUE_STATE,
                ISSUE_NOTE,
                CUSTOM_FIELD_CHAR1,
                CUSTOM_FIELD_CHAR2,
                CUSTOM_FIELD_CHAR3,
                CUSTOM_FIELD_CHAR4,
                CUSTOM_FIELD_CHAR5,
                CUSTOM_FIELD_NUMBER1,
                CUSTOM_FIELD_NUMBER2,
                CUSTOM_FIELD_NUMBER3,
                CUSTOM_FIELD_NUMBER4,
                CUSTOM_FIELD_NUMBER5,
                CUSTOM_FIELD_DATE1,
                CUSTOM_FIELD_DATE2,
                CUSTOM_FIELD_DATE3,
                CUSTOM_FIELD_DATE4,
                CUSTOM_FIELD_DATE5,
                CUSTOM_FIELD_LIST1,
                CUSTOM_FIELD_CHAR6,
                CUSTOM_FIELD_CHAR7,
                CUSTOM_FIELD_CHAR8,
                CUSTOM_FIELD_CHAR9,
                CUSTOM_FIELD_CHAR10,
                CUSTOM_FIELD_CHAR11,
                CUSTOM_FIELD_CHAR16,
                CUSTOM_FIELD_CHAR17,
                CUSTOM_FIELD_CHAR12,
                ASSEET_ID,
                CUSTOM_FIELD_CHAR13,
                CUSTOM_FIELD_CHAR14,
                CUSTOM_FIELD_CHAR15,
                CUSTOM_FIELD_CHAR18,
                CUSTOM_FIELD_CHAR19,
                EMPLOYEE_ID,
                CUSTOM_FIELD_CHAR20,
                CUSTOM_FIELD_DATE9,
                CUSTOM_FIELD_DATE11,
                CUSTOM_FIELD_DATE12,
                CUSTOM_FIELD_DATE13,
                CUSTOM_FIELD_DATE14,
                CUSTOM_FIELD_DATE15,
                CUSTOM_FIELD_DATE16,
                CUSTOM_FIELD_DATE17,
                CUSTOM_FIELD_DATE18,
                CUSTOM_FIELD_DATE19,
                CUSTOM_FIELD_DATE20,
                CUSTOM_FIELD_DATE10,
                CUSTOM_FIELD_DATE6,
                CUSTOM_FIELD_DATE7,
                CUSTOM_FIELD_DATE8,
                CUSTOM_FIELD_NUMBER6,
                CUSTOM_FIELD_NUMBER7,
                CUSTOM_FIELD_NUMBER8,
                CUSTOM_FIELD_NUMBER9,
                CUSTOM_FIELD_NUMBER10,
                CUSTOM_FIELD_NUMBER11,
                CUSTOM_FIELD_NUMBER12,
                CUSTOM_FIELD_NUMBER13,
                CUSTOM_FIELD_NUMBER14,
                CUSTOM_FIELD_NUMBER15,
                CUSTOM_FIELD_NUMBER16,
                CUSTOM_FIELD_NUMBER17,
                CUSTOM_FIELD_NUMBER18,
                CUSTOM_FIELD_NUMBER19,
                CUSTOM_FIELD_NUMBER20,
                SUB_LOCATION,
                FINISH_DATE,
                START_DATE,
                EXPECT_END_DATE,
                PERIOD,
                DEPARTMENT_ID,
                VIOLATION_ID,
                VIOLATION_GROUP_ID,
                VIOLATION_VALUE,
                ASSET_GROUP_ID,
                PARENT_ISSUE_ID,
                CREATED_BY,
                JOB_ORDER_ID
            ) VALUES (
            ISSUE_SEQ.NEXTVAL,
            :REQUEST_ID,
            :ISSUE_TITLE,
            :ISSUE_SUMMARY,
            :ISSUE_PRIORITY,
            :ASSIGN_TO,
            :TARGET_RESOLUTION_DATE,
            :ACTUAL_RESOLUTION_DATE,
            :READ_STATUS,
            :REFERENCE_ID,
            2,
            :ISSUE_TRACK_ID,
            :ISSUE_TYPE,
            :FINAL_RESOLUTION,
            :PROJECT_ID,
            0,
            :CREATED_WO,
            :SUBSIDIARY_ID,
            :CLASSIFICATION,
            sysdate,
            :TYPE_ID,
            :ISSUE_SUB_CLASS,
            :ISSUE_LOCATION,
            :ISSUE_SHIFT,  
            :TOOL,
            :REQUIRE_REPORT,
            :ISSUE_STATE,
            :ISSUE_NOTE,
            :CUSTOM_FIELD_CHAR1,
            :CUSTOM_FIELD_CHAR2,
            :CUSTOM_FIELD_CHAR3,
            :CUSTOM_FIELD_CHAR4,
            :CUSTOM_FIELD_CHAR5,
            :CUSTOM_FIELD_NUMBER1,
            :CUSTOM_FIELD_NUMBER2,
            :CUSTOM_FIELD_NUMBER3,
            :CUSTOM_FIELD_NUMBER4,
            :CUSTOM_FIELD_NUMBER5,
            :CUSTOM_FIELD_DATE1,
            :CUSTOM_FIELD_DATE2,
            :CUSTOM_FIELD_DATE3,
            :CUSTOM_FIELD_DATE4,
            :CUSTOM_FIELD_DATE5,
            :CUSTOM_FIELD_LIST1,
            :CUSTOM_FIELD_CHAR6,
            :CUSTOM_FIELD_CHAR7,
            :CUSTOM_FIELD_CHAR8,
            :CUSTOM_FIELD_CHAR9,
            :CUSTOM_FIELD_CHAR10,
            :CUSTOM_FIELD_CHAR11,
            :CUSTOM_FIELD_CHAR16,
            :CUSTOM_FIELD_CHAR17,
            :CUSTOM_FIELD_CHAR12,
            :ASSEET_ID,
            :CUSTOM_FIELD_CHAR13,
            :CUSTOM_FIELD_CHAR14,
            :CUSTOM_FIELD_CHAR15,
            :CUSTOM_FIELD_CHAR18,
            :CUSTOM_FIELD_CHAR19,
            :EMPLOYEE_ID,
            :CUSTOM_FIELD_CHAR20,
            :CUSTOM_FIELD_DATE9,
            :CUSTOM_FIELD_DATE11,
            :CUSTOM_FIELD_DATE12,
            :CUSTOM_FIELD_DATE13,
            :CUSTOM_FIELD_DATE14,
            :CUSTOM_FIELD_DATE15,
            :CUSTOM_FIELD_DATE16,
            :CUSTOM_FIELD_DATE17,
            :CUSTOM_FIELD_DATE18,
            :CUSTOM_FIELD_DATE19,
            :CUSTOM_FIELD_DATE20,
            :CUSTOM_FIELD_DATE10,
            :CUSTOM_FIELD_DATE6,
            :CUSTOM_FIELD_DATE7,
            :CUSTOM_FIELD_DATE8,
            :CUSTOM_FIELD_NUMBER6,
            :CUSTOM_FIELD_NUMBER7,
            :CUSTOM_FIELD_NUMBER8,
            :CUSTOM_FIELD_NUMBER9,
            :CUSTOM_FIELD_NUMBER10,
            :CUSTOM_FIELD_NUMBER11,
            :CUSTOM_FIELD_NUMBER12,
            :CUSTOM_FIELD_NUMBER13,
            :CUSTOM_FIELD_NUMBER14,
            :CUSTOM_FIELD_NUMBER15,
            :CUSTOM_FIELD_NUMBER16,
            :CUSTOM_FIELD_NUMBER17,
            :CUSTOM_FIELD_NUMBER18,
            :CUSTOM_FIELD_NUMBER19,
            :CUSTOM_FIELD_NUMBER20,
            :SUB_LOCATION,
            :FINISH_DATE,
            :START_DATE,
            :EXPECT_END_DATE,
            :PERIOD,
            :DEPARTMENT_ID,
            :VIOLATION_ID,
            :VIOLATION_GROUP_ID,
            :VIOLATION_VALUE,
            :ASSET_GROUP_ID,
            :PARENT_ISSUE_ID,
            :CREATED_BY,
            :JOB_ORDER_ID
            )
            RETURN ISSUE_ID, REQUEST_ID, ISSUE_TITLE, ISSUE_SUMMARY, ISSUE_PRIORITY, ASSIGN_TO, REFERENCE_TYPE INTO
            :R_ISSUE_ID, :R_REQUEST_ID, :R_ISSUE_TITLE, :R_ISSUE_SUMMARY, :R_ISSUE_PRIORITY, :R_ASSIGN_TO, :R_REFERENCE_TYPE `,
            returns : ["R_ISSUE_ID","R_REQUEST_ID","R_ISSUE_TITLE","R_ISSUE_SUMMARY","R_ISSUE_PRIORITY","R_ASSIGN_TO","R_REFERENCE_TYPE"],
            bindings: [],
            qstring: "",
            requireCommit: true
            },



//////////////////////
insertNewIssue: {
  statement: `
  INSERT INTO issues (
      issue_id,
      REQUEST_ID,
      ISSUE_TITLE,
      ISSUE_SUMMARY,
      ISSUE_PRIORITY,
      ASSIGN_TO,
      TARGET_RESOLUTION_DATE,
      ISSUE_TYPE,
      PROJECT_ID,
      CLASSIFICATION,
      EMPLOYEE_ID
) VALUES (
    ISSUE_SEQ.NEXTVAL,
    :REQUEST_ID,
    :ISSUE_TITLE,
    :ISSUE_SUMMARY,
    :ISSUE_PRIORITY,
    :ASSIGN_TO,
    :TARGET_RESOLUTION_DATE,
    :ISSUE_TYPE,
    :PROJECT_ID,
    :CLASSIFICATION,
    :EMPLOYEE_ID
    )
  RETURN issue_id, ISSUE_TITLE , ISSUE_SUMMARY, ISSUE_PRIORITY, ASSIGN_TO,
   TARGET_RESOLUTION_DATE, ISSUE_TYPE, PROJECT_ID , CLASSIFICATION, REQUEST_ID, EMPLOYEE_ID INTO
    :R_issue_id, :R_ISSUE_TITLE , :R_ISSUE_SUMMARY, :R_ISSUE_PRIORITY, :R_ASSIGN_TO,
     :R_TARGET_RESOLUTION_DATE, :R_ISSUE_TYPE, :R_PROJECT_ID, :R_CLASSIFICATION, :R_REQUEST_ID , :R_EMPLOYEE_ID `,
returns: ["R_issue_id","R_ISSUE_TITLE","R_ISSUE_SUMMARY","R_ISSUE_PRIORITY","R_ASSIGN_TO",
"R_TARGET_RESOLUTION_DATE","R_ISSUE_TYPE","R_PROJECT_ID","R_CLASSIFICATION", "R_REQUEST_ID", "R_EMPLOYEE_ID"],
bindings: [],
qstring: "",
requireCommit: true
},
    getMaxissuesAssignment :
    {
      statement : `SELECT SI.ISSUE_ID,RQ.REQUEST_STATUS,
                     SI.REQUEST_ID,RQ.CREATED_BY,SI.ASSIGN_TO,
                     (select max(IA.ASSIGNMENT_ID) from ISSUE_ASSIGNMENTS ia where IA.ISSUE_ID=SI.ISSUE_ID and IA.ASSIGNMENT_STATUS=1 and IA.EMPLOYEE_ID=:p_employeeId)ASSIGNMENT_ID,
                     SI.ISSUE_TITLE, SI.ISSUE_SUMMARY,
                     SI.ISSUE_PRIORITY,SI.TARGET_RESOLUTION_DATE,
                     SI.READ_STATUS, SI.ISSUE_TRACK_ID,
                     SI.ISSUE_TYPE,SI.FINAL_RESOLUTION,
                     PJ.PRIMARY_NAME projectNameAr,
                     PJ.SECONDARY_NAME projectNameEr,
                     CS.AR_NAME clientNameAR,CS.EN_NAME clientNameEn,
                     CASE SI.REFERENCE_TYPE WHEN 2 THEN (SELECT COMMITTEE_NAME_AR from COMMITTEE WHERE COMMITTEE_ID = SI.REFERENCE_ID )  END COMMITTEE_NAME_AR ,
                     CASE SI.REFERENCE_TYPE WHEN 2 THEN (SELECT COMMITTEE_NAME_EN from COMMITTEE WHERE COMMITTEE_ID = SI.REFERENCE_ID  )  END COMMITTEE_NAME_EN
                    FROM ISSUES SI,projects pj ,requests rq,clients cs
                    WHERE CS.CLIENT_ID =PJ.CLIENT_ID AND SI.PROJECT_ID = PJ.PROJECT_ID
                    AND SI.REQUEST_ID  =RQ.REQUEST_ID
                    AND ((RQ.CREATED_BY=:p_employeeId and RQ.REQUEST_STATUS <>8) OR (SI.ASSIGN_TO=:p_employeeId and RQ.REQUEST_STATUS=1) )
                    AND NVL(CS.DELETED,0)=0 AND NVL(PJ.DELETED,0)=0 AND NVL(SI.DELETED,0)=0 order by RQ.CREATION_DATE DESC `,
      bindings :[],
      qstring : "",
      requireCommit : false
    },


    getIssuesByEmpID:{
       statement:`SELECT I.ISSUE_ID,
       I.REQUEST_ID,
       I.ISSUE_TITLE,
       I.ISSUE_SUMMARY,
       I.ISSUE_PRIORITY,
       I.ASSIGN_TO,
       I.TARGET_RESOLUTION_DATE,
       I.ACTUAL_RESOLUTION_DATE,
       I.READ_STATUS,
       I.REFERENCE_ID,
       I.REFERENCE_TYPE,
       I.ISSUE_TRACK_ID,
       I.ISSUE_TYPE,
       I.FINAL_RESOLUTION,
       I.PROJECT_ID,
       I.CREATED_WO,
       I.SUBSIDIARY_ID,
       I.CLASSIFICATION,
       I.CREATION_DATE,
       I.TYPE_ID,
       I.ISSUE_SUB_CLASS,
       I.ISSUE_LOCATION,
       I.SHIFT,
       I.TOOL,
       I.REQUIRE_REPORT,
       I.ISSUE_STATE,
       I.ISSUE_NOTE,
       I.ASSEET_ID,
       I.EMPLOYEE_ID,
       I.SUB_LOCATION,
       I.FINISH_DATE,
       I.START_DATE,
       I.EXPECT_END_DATE,
       I.PERIOD,
       I.DEPARTMENT_ID,
       I.VIOLATION_ID,
       I.VIOLATION_GROUP_ID,
       I.VIOLATION_VALUE,
       I.ASSET_GROUP_ID
  FROM ISSUES i , requests r
  where i.REQUEST_ID=r.REQUEST_ID
  and r.created_by=:EMPLOYEE_ID
  and i.type_id=12274`,


      bindings :[],
      qstring : "",
      requireCommit : false

    },
    insertNewIssueAssignments: {
          statement: `
          INSERT INTO ISSUE_ASSIGNMENTS (
                         ASSIGNMENT_ID,
                          ISSUE_ID,
                          ASSIGNMENT_STATUS,
                         ASSIGNMENT_OPEN,
                         ASSIGNMENT_DATE,
                          ASSIGNMENT_COMMENTS,
                         EMPLOYEE_ID,
                         DELETED,
                          SUBSIDIARY_ID)
                      VALUES (
                              ISSUE_ASSIGNMENT_SEQ.NEXTVAL,
                              :ISSUE_ID,
                              :ASSIGNMENT_STATUS,
                              :ASSIGNMENT_OPEN,
                              SYSDATE,
                              :ASSIGNMENT_COMMENTS,
                              :EMPLOYEE_ID,
                              0,
                              :SUBSIDIARY_ID

                               )

                          RETURN  ISSUE_ID , ASSIGNMENT_STATUS , ASSIGNMENT_OPEN , EMPLOYEE_ID , ASSIGNMENT_DATE , ASSIGNMENT_COMMENTS INTO :R_ISSUE_ID  , :R_ASSIGNMENT_STATUS , :R_ASSIGNMENT_OPEN , :R_EMPLOYEE_ID , :R_ASSIGNMENT_DATE , :R_ASSIGNMENT_COMMENTS`,
                  returns: ["R_ISSUE_ID" , "R_ASSIGNMENT_STATUS" , "R_ASSIGNMENT_OPEN" , "R_EMPLOYEE_ID" , "R_ASSIGNMENT_DATE", "R_ASSIGNMENT_COMMENTS"],
                  bindings: [],
                  qstring: "",
                  requireCommit: true
                      },

                      getIssues:{
                        statement:`SELECT
                        ISS.ISSUE_ID                ,
                        ISS.REQUEST_ID              ,
                        (SELECT PP.PRIMARY_NAME FROM PROJECTS PP WHERE PP.PROJECT_ID=ISS.PROJECT_ID) PROJECT_PRIMARYNAME ,
                        (SELECT PP.SECONDARY_NAME FROM PROJECTS PP WHERE PP.PROJECT_ID=ISS.PROJECT_ID) PROJECT_SECONDARYNAME ,
                        GETEMPNAME_LANG(ISS.CREATED_BY,1,1) CREATED_BY_EMP_NAME_AR,
                        GETEMPNAME_LANG(ISS.CREATED_BY,1,2) CREATED_BY_EMP_NAME_EN,
                        GETEMPNAME_LANG(ISS.ASSIGN_TO ,1,1) ASSIGN_TO_EMP_NAME_AR,
                        GETEMPNAME_LANG(ISS.ASSIGN_TO ,1,2) ASSIGN_TO_EMP_NAME_EN,
                        ISS.ISSUE_TITLE             ,
                        ISS.ISSUE_SUMMARY           ,
                        ISS.ISSUE_PRIORITY          ,
                        ISS.ASSIGN_TO               ,
                        ISS.TARGET_RESOLUTION_DATE  ,
                        ISS.ACTUAL_RESOLUTION_DATE  ,
                        ISS.READ_STATUS             ,
                        ISS.REFERENCE_ID            ,
                        ISS.REFERENCE_TYPE          ,
                        ISS.ISSUE_TRACK_ID          ,
                        ISS.ISSUE_TYPE              ,
                        ISS.FINAL_RESOLUTION        ,
                        ISS.PROJECT_ID              ,
                        ISS.DELETED                 ,
                        ISS.DELETED_BY              ,
                        ISS.DELETED_DATE            ,
                        ISS.CREATED_WO              ,
                        ISS.SUBSIDIARY_ID           ,
                        ISS.CLASSIFICATION          ,
                        ISS.CREATION_DATE           ,
                        ISS.TYPE_ID                 ,
                        ISS.ISSUE_SUB_CLASS         ,
                        ISS.ISSUE_LOCATION          ,
                        ISS.SHIFT                   ,
                        ISS.TOOL                    ,
                        ISS.REQUIRE_REPORT          ,
                        ISS.ISSUE_STATE             ,
                        ISS.ISSUE_NOTE              ,
                        ISS.SUB_LOCATION            ,
                        ISS.FINISH_DATE             ,
                        ISS.START_DATE              ,
                        ISS.EXPECT_END_DATE         ,
                        ISS.PERIOD                  ,
                        ISS.DEPARTMENT_ID           ,
                        ISS.VIOLATION_ID            ,
                        ISS.VIOLATION_GROUP_ID      ,
                        ISS.VIOLATION_VALUE         ,
                        ISS.ASSET_GROUP_ID          ,
                        ISS.PARENT_ISSUE_ID         ,
                        ISS.CREATED_BY              ,
                        ISS.JOB_ORDER_ID
                        FROM ISSUES ISS`,
                 
                 
                       bindings :[],
                       qstring : "",
                       requireCommit : false
                 
                     }


}
module.exports = statements;
