
let statements = {
    getAllJobVacancy: {
            statement :`
            SELECT ID,
                   JOB_CODE,
                   JOB_NAME_EN,
                   JOB_NAME_AR,
                   POSITION_ID,
                   EXPERIENCE_YEARS,
                   RELIGION,
                   MAX_SALARY,
                   JOB_SKILLS,
                   RESPONSIBILITY,
                   TECHNICAL_ID,
                   IS_PUBLIC,
                   OPEN_POSITIONS,
                   START_DATE,
                   END_DATE,
                   IS_URGENT,
                   COMMENTS_TO_HR,
                   ADV_SOCIAL,
                   ADV_INVITATIONS,
                   ADV_PAID,
                   ADV_COMMENTS_TO_HR,
                   ADV_SOCIAL_REPLY,
                   ADV_INVITATIONS_REPLY,
                   ADV_PAID_REPLY,
                   ADV_SOCIAL_DATE,
                   ADV_INVITATIONS_DATE,
                   ADV_PAID_DATE,
                   ADV_HR_COMMENTS,
                   SENT_FLAG,
                   STATUS,
                   SENDER_ID,
                   SENT_ON,
                   CREATED_BY,
                   CREATED_ON,
                   LAST_MODIFIED_BY,
                   LAST_MODIFIED_ON,
                   STATUS_ENABLED,
                   IS_PUBLIC_REPLY,
                   IS_PUBLIC_COMMENT,
                   IS_PUBLIC_DATE,
                   ADV_SOCIAL_COMMENT,
                   ADV_INVITATION_COMMENT,
                   ADV_PAID_COMMENT,
                   MAX_SALARY_CURR,
                   NATIONALITY,
                   JOB_LOCATION_COUNTRY,
                   JOB_LOCATION_CITY,
                   HR_REJECT_COMMENT,
                   EXPERIENCE_YEARS_FROM,
                   EXPERIENCE_YEARS_TO,
                   REACTIVATEFLAG,
                   DELETED,
                   DELETED_BY,
                   DELETED_DATE,
                   SENT_TO_HR_FLAG
              FROM JOB_VACANCY `,
            returns: [],
            bindings: [],
            qstring: "",
            requireCommit: false
    },
  
    getOneJobVacancyByID:{
        statement:`SELECT ID,
        JOB_CODE,
        JOB_NAME_EN,
        JOB_NAME_AR,
        POSITION_ID,
        EXPERIENCE_YEARS,
        RELIGION,
        MAX_SALARY,
        JOB_SKILLS,
        RESPONSIBILITY,
        TECHNICAL_ID,
        IS_PUBLIC,
        OPEN_POSITIONS,
        START_DATE,
        END_DATE,
        IS_URGENT,
        COMMENTS_TO_HR,
        ADV_SOCIAL,
        ADV_INVITATIONS,
        ADV_PAID,
        ADV_COMMENTS_TO_HR,
        ADV_SOCIAL_REPLY,
        ADV_INVITATIONS_REPLY,
        ADV_PAID_REPLY,
        ADV_SOCIAL_DATE,
        ADV_INVITATIONS_DATE,
        ADV_PAID_DATE,
        ADV_HR_COMMENTS,
        SENT_FLAG,
        STATUS,
        SENDER_ID,
        SENT_ON,
        CREATED_BY,
        CREATED_ON,
        LAST_MODIFIED_BY,
        LAST_MODIFIED_ON,
        STATUS_ENABLED,
        IS_PUBLIC_REPLY,
        IS_PUBLIC_COMMENT,
        IS_PUBLIC_DATE,
        ADV_SOCIAL_COMMENT,
        ADV_INVITATION_COMMENT,
        ADV_PAID_COMMENT,
        MAX_SALARY_CURR,
        NATIONALITY,
        JOB_LOCATION_COUNTRY,
        JOB_LOCATION_CITY,
        HR_REJECT_COMMENT,
        EXPERIENCE_YEARS_FROM,
        EXPERIENCE_YEARS_TO,
        REACTIVATEFLAG,
        DELETED,
        DELETED_BY,
        DELETED_DATE,
        SENT_TO_HR_FLAG
   FROM JOB_VACANCY
   WHERE  ID = :ID `,
        returns: [],
        bindings: [],
        qstring: "",
        requireCommit: false
    }
  }
  
  module.exports = statements ;
  