export const getLeftMenuData: any[] = [
  // {
  //   title: 'Settings',
  //   translateKeys: 'SETTINGS',
  //   key: 'settings',
  //   icon: 'icmn icmn-cog utils__spin-delayed--pseudo-selector',
  // },
  // {
  //   title: 'Documentation',
  //   translateKeys: 'DOCUMENTATION',
  //   key: 'documentation',
  //   url: 'https://docs.cleanuitemplate.com/angular/getting-started',
  //   target: '_blank',
  //   icon: 'icmn icmn-books',
  // },
  // {
  //   divider: true,
  // },
  {
    title: 'Home Page',
    translateKeys: 'HOME_PAGE',
    key: 'home',
    // url: '/medan/home',
    url: '/medan/home/reports',
    icon: 'icmn icmn-home',
    pro: true,
  },
  {
    title: 'My Issues',
    translateKeys: 'MY_ISSUES',
    key: 'home',
    url: '/medan/home/myissues',
    icon: 'icmn icmn-myissues',
    pro: true,
  },
  {
    title: 'My Issues Add',
    translateKeys: 'MY_ISSUES_ADD',
    key: 'home',
    url: '/medan/home/myissues/add',
    icon: 'icmn icmn-myissues',
    pro: true,
  },
  
  {
    title: 'My Issue Details',
    translateKeys: 'MY_ISSUE_DETAILS',
    key: 'home',
    url: '/medan/home/myissues/details',
    icon: 'icmn icmn-myissues',
    pro: true
  },
  {
    title: 'Work Order',
    translateKeys: 'WORK_ORDER',
    key: 'workorder',
    url: '/medan/work-order/report',
    icon: 'icmn icmn-home',
    pro: true,
  },
  {
    title: 'New Incident Report',
    translateKeys: 'NEW_INCIDENT_REPORT',
    key: 'workorder',
    url: '/medan/work-order/incident',
    icon: 'icmn icmn-home',
    pro: true,
  },
  {
    title: 'New Incident Report Add ',
    translateKeys: 'NEW_INCIDENT_REPORT_ADD_',
    key: 'workorder',
    url: '/medan/work-order/incident/add',
    icon: 'icmn icmn-home',
    pro: true,
  },
  {
    title: 'Meeting Details',
    translateKeys: 'MEETING_DETAILS',
    key: 'home',
    url: '/medan/home/details',
    icon: 'icmn icmn-home',
    pro: true,
  },
  {
    key: 'home',
    title: 'Meeting Form',
    translateKeys: 'MEETING_FORM',
    url: '/medan/home/meetingbox/add',
    pro: true,
  },
  {
    key: 'home',
    title: 'Commitee Member Form',
    translateKeys: 'COMMITEE_MEMBER_FORM',
    url: '/medan/home/commitee/{var}/details/add',
    pro: true,
  },
  {
    key: 'home',
    title: 'Add Meeting Form',
    translateKeys: 'ADD_MEETING_FORM',
    url: '/medan/home/commitee/{var}/details/addMeeting',
    pro: true,
  },
  {
    key: 'home',
    title: 'Add Meeting Form',
    translateKeys: 'ADD_MEETING_FORM',
    url: '/medan/home/meetingbox/{var}/add',
    pro: true,
  },
  {
    key: 'home',
    title: 'Commitee Member Form',
    translateKeys: 'COMMITEE_MEMBER_FORM',
    url: '/medan/home/meetingbox/{var}/add/add',
    pro: true,
  },
  {
    key: 'home',
    title: 'Commitee Details All',
    translateKeys: 'COMMITEE_DETAILS_ALL',
    url: '/medan/home/commitee/{var}/details',
    pro: true,
  },
  {
    key: 'home',
    title: 'Details',
    translateKeys: 'DETAILS',
    url: '/medan/home/meeting/{var}/details',
    pro: true,
  },
  {
    title: 'Dash Bord',
    translateKeys: 'DASH_BORD',
    key: 'dashbord',
    url: '/medan/home/dashbord',
    icon: 'icmn icmn-dashbord',
    pro: true,
  },
  {
    title: 'Reports',
    translateKeys: 'REPORTS',
    key: 'reports',
    url: '/medan/home/reports',
    icon: 'icmn icmn-reports',
    pro: true,
  },
  {
    title: 'Variance Report',
    translateKeys: 'VARIANCE_REPORT',
    key: 'variance-report',
    url: '/medan/reports-list/variance-report',
    icon: 'icmn icmn-variance-report',
    pro: true,
  },
  {
    title: 'No OF Cups',
    translateKeys: 'NO_OF_CUPS',
    key: 'no-of-cups',
    url: '/medan/reports-list/no-of-cups',
    icon: 'icmn icmn-reports-list',
    pro: true,
  },
  {
    title: 'Work Order Status in Location Or Shift',
    translateKeys: 'Work Order Status in Location Or Shift',
    key: 'Work Order Status in Location Or Shift',
    url: '/medan/reports-list/activities',
    icon: 'icmn icmn-Activities',
    pro: true,
  },
  {
    title: 'Employee Work Orders',
    translateKeys: 'Employee Work Orders',
    key: 'Employee Work Orders',
    url: '/medan/reports-list/employee-activities',
    icon: 'icmn icmn-employee-activities',
    pro: true,
  },
  {
    title: 'Zamzam Water Withdraw',
    translateKeys: 'Zamzam Water Withdraw',
    key: 'Zamzam Water Withdraw',
    url: '/medan/reports-list/zamzam-water',
    icon: 'icmn icmn-zamzam-water',
    pro: true,
  },
  {
    title: 'Clean Equipment Count',
    translateKeys: 'CLEAN_EQUIPMENT_COUNT',
    key: 'clean equipment count',
    url: '/medan/reports-list/clean-equipment-count',
    icon: 'icmn icmn-clean-equipment-count',
    pro: true,
  },
  {
    title: 'Work Permissions',
    translateKeys: 'WORK_PERMISSIONS',
    key: 'work permissions',
    url: '/medan/reports-list/work-permissions',
    icon: 'icmn icmn-work-permissions',
    pro: true,
  },
  {
    title: 'Contractor Evaluation',
    translateKeys: 'CONTRACTOR_EVALUATION',
    key: 'contractor evaluation',
    url: '/medan/reports-list/contractor-evaluation',
    icon: 'icmn icmn-contractor-evaluation',
    pro: true,
  },
  {
    title: 'Contractor Information',
    translateKeys: 'CONTRACTOR_INFORMATION',
    key: 'contractor information',
    url: '/medan/reports-list/contractor-information',
    icon: 'icmn icmn-contractor-permission',
    pro: true,
  },
  {
    title: 'Items Balance in Stores',
    translateKeys: 'Items Balance in Stores',
    key: 'Items Balance in Stores',
    url: '/medan/reports-list/items-unit',
    icon: 'icmn icmn-items-unit',
    pro: true,
  },
  {
    title: 'Fines',
    translateKeys: 'FINES',
    key: 'Fines',
    url: '/medan/reports-list/fines',
    icon: 'icmn icmn-fines',
    pro: true,
  },
  {
    title: 'Work Permissions Description',
    translateKeys: 'WORK_PERMISSIONS_DESCRIPTION',
    key: 'work permission desc',
    url: '/medan/reports-list/work-permissions-desc',
    icon: 'icmn icmn-work-permission-description',
    pro: true,
  },
  {
    title: 'Month Increment Percentage',
    translateKeys: 'MONTH_INCREMENT_PERCENTAGE',
    key: 'month increment percentage',
    url: '/medan/reports-list/month-increment-percentage',
    icon: 'icmn icmn-month-increment-percentage',
    pro: true,
  },
  {
    title: 'Equipment Maintenance Status',
    translateKeys: 'Equipment Maintenance Status',
    key: 'Equipment Maintenance Status',
    url: '/medan/reports-list/equipment-maintenance',
    icon: 'icmn icmn-equipment-maintenance',
    pro: true,
  },
  {
    title: 'Incident Data in Location or Shift',
    translateKeys: 'Incident Data in Location or Shift',
    key: 'Incident Data in Location or Shift',
    url: '/medan/reports-list/incidents',
    icon: 'icmn icmn-incidents',
    pro: true,
  },
  {
    title: 'Employees Violations',
    translateKeys: 'Employees Violations',
    key: 'Employees Violations',
    url: '/medan/reports-list/employees-issues',
    icon: 'icmn icmn-employee-issues',
    pro: true,
  },
  {
    title: 'Items',
    translateKeys: 'ITEMS',
    key: 'Items',
    url: '/medan/reports-list/items',
    icon: 'icmn icmn-items',
    pro: true,
  },
  {
    title: 'Clean Bases',
    key: 'Clean Bases',
    url: '/medan/reports-list/clean-bases',
    translateKeys: 'CLEAN_BASES',
    icon: 'icmn icmn-clean-bases',
    pro: true,
  },
  {
    title: 'Materials used in Contracts',
    key: 'Materials used in Contracts',
    url: '/medan/reports-list/materials',
    translateKeys: 'Materials used in Contracts',
    icon: 'icmn icmn-materials',
    pro: true,
  },
  {
    title: 'Equipment Work Orders',
    key: 'Equipment Work Orders',
    url: '/medan/reports-list/equipment-order',
    translateKeys: 'Equipment Work Orders',
    icon: 'icmn icmn-equipment-maintain-order',
    pro: true,
  },
  {
    title: 'Equipment Count',
    key: 'Equipment Count',
    url: '/medan/reports-list/equipment-count',
    translateKeys: 'Equipment Count',
    icon: 'icmn icmn-equipment-count',
    pro: true,
  },
  {
    title: 'Equipment Data',
    key: 'Equipment Data',
    url: '/medan/reports-list/equipment-data',
    translateKeys: 'Equipment Data',
    icon: 'icmn icmn-equipment-data',
    pro: true,
  },
  {
    title: 'Work Orders By Maintenance Type',
    key: 'Work Orders By Maintenance Type',
    url: '/medan/reports-list/operation-activities',
    translateKeys: 'Work Orders By Maintenance Type',
    icon: 'icmn icmn-operation-activities',
    pro: true,
  },
  {
    title: 'Equipment Operation Status',
    key: 'Equipment Operation Status',
    url: '/medan/reports-list/equipment-main-status',
    translateKeys: 'Equipment Operation Status',
    icon: 'icmn icmn-equipment-main-status',
    pro: true,
  },
  {
    title: 'Equipment Status',
    key: 'Equipment Status',
    url: '/medan/reports-list/equipment-status',
    translateKeys: 'Equipment Status',
    icon: 'icmn icmn-equipment-status',
    pro: true,
  },
  {
    title: 'Activities And Services',
    key: 'Activities And Services',
    url: '/medan/reports-list/activities-services',
    translateKeys: 'Activities And Services',
    icon: 'icmn icmn-activities-and-services',
    pro: true,
  },
  {
    title: 'Work Order',
    key: 'Work Order',
    url: '/medan/reports-list/work-order',
    translateKeys: 'WORK_ORDER',
    icon: 'icmn icmn-work-order',
    pro: true,
  },
  {
    title: 'Clean Equipment Filter',
    key: 'Clean Equipment Filter',
    url: '/medan/reports-list/clean-equipment-filter',
    translateKeys: 'Clean Equipment Filter',
    icon: 'icmn icmn-clean-equipment-filter',
    pro: true,
  },
  // {
  //   title: 'Shift Status',
  //   key: 'Shift Status',
  //   url: '/medan/reports-list/shift-status',
  //   translateKeys: 'SHIFT_STATUS',
  //   icon: 'icmn icmn-shift-status',
  //   pro: true,
  // },
  {
    title: 'Volume of Waste',
    key: 'Volume of Waste',
    url: '/medan/reports-list/daily-waste',
    translateKeys: 'Volume of Waste',
    icon: 'icmn icmn-daily-waste',
    pro: true,
  },
  {
    title: 'Items reorder limit',
    key: 'Items reorder limit',
    url: '/medan/reports-list/purchasing-order',
    translateKeys: 'Items reorder limit',
    icon: 'icmn icmn-purchasing-order',
    pro: true,
  },
]
export const getTopMenuData: any[] = [
  {
    title: 'Settings',
    translateKeys: 'SETTINGS',
    key: 'settings',
    icon: 'icmn icmn-cog utils__spin-delayed--pseudo-selector',
  },
  {
    title: 'Documentation',
    translateKeys: 'DOCUMENTATION',
    key: 'documentation',
    url: 'https://docs.cleanuitemplate.com/angular/getting-started',
    target: '_blank',
    icon: 'icmn icmn-books',
  },
  {
    divider: true,
  },
 
]
